In [1]:
%config Completer.use_jedi = False
import warnings
warnings.filterwarnings("ignore")
import datetime
import tensorflow as tf
import pandas as pd
import numpy as np
import os, sys
import time
sys.path.append(os.path.join(os.getcwd(), '../common'))
from utils import timer, save, load
pd.set_option('display.max_columns', None)

2023-01-07 14:01:39.857445: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

# Tutorial

- concept
    - Cerebro: BackTrader的基石，所有操作都是基于Cerebro
    - Feed: 将运行策略所需的基础数据加载到Cerebro中，一般为K线数据
    - Indicator: BackTrader自带的指标，并集成了talib中的指标，我们也可以选择继承一个Indicator实现自己的指标
    - Strategy: 交易策略。这里是整个过程中最复杂的部分，需要我们计算买入/卖出信号
    - Analyzer: 分析器，以图形的风险收益等指标对交易策略的回测结果进行分析评价
    - Order: 订单，记录了与当前订单相关的所有数据
    - Trader: 交易，记录了与当前交易相关的所有数据
    - Position: 持仓，记录了与当前持仓相关的所有数据
    - Broker: 可以理解为经纪人，整个策略的初始资金、交易费率、滑点等参数需要通过Broker进行设置
    - Observer: 观察者，对数据进行监控观察，比如资金曲线等
    - Plotting: 可视化组件

[Yahoo Data Source](https://sg.finance.yahoo.com/quote/AAPL/history?p=AAPL)

In [2]:
import backtrader as bt # 导入 Backtrader
 
# 实例化 cerebro
cerebro = bt.Cerebro()
# 打印初始资金
print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
# 启动回测
cerebro.run()
# 打印回测完成后的资金
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

Starting Portfolio Value: 10000.00
Final Portfolio Value: 10000.00

In [3]:
TRADE_MONEY_DIR = os.path.join(os.getcwd(), f'../DataStore/trade_money/')

In [4]:
TRADE_MONEY_DIR

'/Users/qingbin.zhuang/Personal/StockProject/Debug/../DataStore/trade_money/'

In [5]:
df_trade_money = pd.DataFrame()
for _file in os.listdir(TRADE_MONEY_DIR):
    if not _file.endswith('pkl'):
        continue
    df_trade_money_tmp = load(f'{TRADE_MONEY_DIR}/{_file}')
    df_trade_money = pd.concat([df_trade_money, df_trade_money_tmp])

In [6]:
df_trade_money['trade_date'].min(), df_trade_money['trade_date'].max()

('20200102', '20221215')

In [7]:
df_trade_money01 = df_trade_money[(df_trade_money.ts_code == '000001.SZ')]
df_trade_money01['trade_date'] = pd.to_datetime(df_trade_money01['trade_date'])

In [8]:
df_trade_money01.head(2)

,ts_code,area,industry,list_date,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,up_limit,down_limit,turnover_rate,turnover_rate_f,volume_ratio,pe,pe_ttm,pb,ps,ps_ttm,dv_ratio,dv_ttm,total_share,float_share,free_share,total_mv,circ_mv,buy_sm_vol,buy_sm_amount,sell_sm_vol,sell_sm_amount,buy_md_vol,buy_md_amount,sell_md_vol,sell_md_amount,buy_lg_vol,buy_lg_amount,sell_lg_vol,sell_lg_amount,buy_elg_vol,buy_elg_amount,sell_elg_vol,sell_elg_amount,net_mf_vol,net_mf_amount
0,000001.SZ,深圳,银行,19910403,2022-07-18,13.25,13.44,13.21,13.39,13.24,0.15,1.1329,1153505.81,1536340.973,14.56,11.92,0.5944,1.3411,0.74,7.1512,6.6535,0.7728,1.5341,1.4951,1.3443,NaN,1.940592e+06,1.940552e+06,860088.1226,2.598452e+07,2.598399e+07,290314.0,38652.82,237985.0,31714.35,374690.0,49911.00,300986.0,40108.60,287278.0,38264.27,363162.0,48355.13,201224.0,26806.01,251373.0,33456.01,-79179.0,-10440.19
0,000001.SZ,深圳,银行,19910403,2021-08-03,17.99,18.15,17.66,17.89,18.01,-0.12,-0.6663,896948.57,1609422.575,19.81,16.21,0.4622,1.0428,0.83,12.0012,11.3782,1.1604,2.2611,2.2056,1.2186,1.0061,1.940592e+06,1.940575e+06,860111.3751,3.471719e+07,3.471689e+07,177206.0,31780.95,231348.0,41545.06,292854.0,52540.94,300370.0,53911.82,295290.0,52990.36,264725.0,47446.96,131599.0,23630.01,100505.0,18038.41,-140762.0,-25138.50

In [9]:
df_trade_money01['trade_date'].min(), df_trade_money01['trade_date'].max()

(Timestamp('2020-01-02 00:00:00'), Timestamp('2022-12-15 00:00:00'))

In [10]:
class TusharePdData(bt.feeds.PandasData):
    '''
    从Tushare读取A股票数据日线
    '''
    params = (
        ('datetime', "trade_date"),
        ('open', "open"),
        ('high', "high"),
        ('low', "low"),
        ('close', "close"),
        ('volume', "vol"),
        ('openinterest', None),
        ('change', "change")
    )
    
data = TusharePdData(dataname=df_trade_money01, 
                     fromdate=datetime.datetime.strptime("20200110", "%Y%m%d"), 
                     todate=datetime.datetime.strptime("20221215", "%Y%m%d"))

In [11]:
cerebro = bt.Cerebro()
cerebro.adddata(data)
cerebro.run()
# cerebro.plot()

In [12]:
cerebro.plot()

ImportError: Matplotlib seems to be missing. Needed for plotting support

In [16]:
class TestStrategy(bt.Strategy):
    """
    继承并构建自己的bt策略
    """

    def log(self, txt, dt=None, doprint=False):
        ''' 日志函数，用于统一输出日志格式 '''
        if doprint:
            dt = dt or self.datas[0].datetime.date(0)
            print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):

        # 初始化相关数据
        self.dataclose = self.datas[0].close
        self.order = None
        self.buyprice = None
        self.buycomm = None

        # 五日移动平均线
        self.sma5 = bt.indicators.SimpleMovingAverage(
            self.datas[0], period=10)
        # 十日移动平均线
        self.sma10 = bt.indicators.SimpleMovingAverage(
            self.datas[0], period=20)

    def notify_order(self, order):
        """
        订单状态处理

        Arguments:
            order {object} -- 订单状态
        """
        if order.status in [order.Submitted, order.Accepted]:
            # 如订单已被处理，则不用做任何事情
            return

        # 检查订单是否完成
        if order.status in [order.Completed]:
            if order.isbuy():
                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            self.bar_executed = len(self)

        # 订单因为缺少资金之类的原因被拒绝执行
        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.log('Order Canceled/Margin/Rejected')

        # 订单状态处理完成，设为空
        self.order = None

    def notify_trade(self, trade):
        """
        交易成果
        
        Arguments:
            trade {object} -- 交易状态
        """
        if not trade.isclosed:
            return

        # 显示交易的毛利率和净利润
        self.log('OPERATION PROFIT, GROSS %.2f, NET %.2f' %
                 (trade.pnl, trade.pnlcomm), doprint=True)

    def next(self):
        ''' 下一次执行 '''

        # 记录收盘价
        self.log('Close, %.2f' % self.dataclose[0])

        # 是否正在下单，如果是的话不能提交第二次订单
        if self.order:
            return

        # 是否已经买入
        if not self.position:
            # 还没买，如果 MA5 > MA10 说明涨势，买入
            if self.sma5[0] > self.sma10[0]:
                self.order = self.buy()
        else:
            # 已经买了，如果 MA5 < MA10 ，说明跌势，卖出
            if self.sma5[0] < self.sma10[0]:
                self.order = self.sell()

    def stop(self):
        self.log(u'(金叉死叉有用吗) Ending Value %.2f' %
                 (self.broker.getvalue()), doprint=True)

In [17]:
# 初始化模型
cerebro = bt.Cerebro()

# 构建策略
strats = cerebro.addstrategy(TestStrategy)
# 每次买100股
cerebro.addsizer(bt.sizers.FixedSize, stake=100)

# 加载数据到模型中
# data = bt.feeds.GenericCSVData(
#     dataname='600519.csv',
#     fromdate=datetime.datetime(2010, 1, 1),
#     todate=datetime.datetime(2020, 4, 12),
#     dtformat='%Y%m%d',
#     datetime=2,
#     open=3,
#     high=4,
#     low=5,
#     close=6,
#     volume=10
# )

cerebro.adddata(data)

# 设定初始资金和佣金
cerebro.broker.setcash(1000000.0)
cerebro.broker.setcommission(0.005)

# 策略执行前的资金
print('启动资金: %.2f' % cerebro.broker.getvalue())

# 策略执行
cerebro.run()

启动资金: 1000000.00
2022-10-17, OPERATION PROFIT, GROSS -298.00, NET -310.91
2022-09-28, OPERATION PROFIT, GROSS -220.00, NET -233.19
2022-10-28, OPERATION PROFIT, GROSS -251.00, NET -262.88
2021-08-26, (金叉死叉有用吗) Ending Value 999561.67

In [18]:
cerebro.plot()

ImportError: cannot import name 'warnings' from 'matplotlib.dates' (/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/site-packages/matplotlib/dates.py)

## MA策略

In [88]:
import backtrader as bt

In [140]:
print(bt)

<module 'backtrader' from '/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/site-packages/backtrader/__init__.py'>

In [141]:
bt.feeds.PandasData?

In [132]:
class MAcrossover(bt.Strategy):
    # Moving average parameters
    params = (('pfast', 20), ('pslow', 50))
    
    def log(self, txt, dt = None):
        dt = dt or self.datas[0].datetime.date(0)
        print(f'{dt.isoformat()} {txt}')
        
    def __init__(self):
        self.dataclose = self.datas[0].close
        
        # Order variable will contain ongoing order details/status
        self.order = None

        # Instantiate moving averages
        self.slow_sma = bt.indicators.MovingAverageSimple(self.datas[0], 
                        period=self.params.pslow)
        self.fast_sma = bt.indicators.MovingAverageSimple(self.datas[0], 
                        period=self.params.pfast)
        
    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            return
        
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(f'BUY EXECUTED, {order.executed.price:.2f}')
            elif order.issell():
                self.log(f'SELL EXECUTED, {order.executed.price:.2f}')
            self.bar_executed = len(self)
            
        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.log('Order Canceled/Margin/Rejected')

        # Reset orders
        self.order = None
        
    def next(self):
        # Check for open orders
        if self.order:
            return

        # Check if we are in the market
        if not self.position:
            # We are not in the market, look for a signal to OPEN trades

            #If the 20 SMA is above the 50 SMA
            if self.fast_sma[0] > self.slow_sma[0] and self.fast_sma[-1] < self.slow_sma[-1]:
                self.log(f'BUY CREATE {self.dataclose[0]:2f}')
                # Keep track of the created order to avoid a 2nd order
                self.order = self.buy()
            #Otherwise if the 20 SMA is below the 50 SMA   
            elif self.fast_sma[0] < self.slow_sma[0] and self.fast_sma[-1] > self.slow_sma[-1]:
                self.log(f'SELL CREATE {self.dataclose[0]:2f}')
                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()
        else:
            # We are already in the market, look for a signal to CLOSE trades
            if len(self) >= (self.bar_executed + 5):
                self.log(f'CLOSE CREATE {self.dataclose[0]:2f}')
                self.order = self.close()

In [134]:
import datetime
import backtrader as bt

cerebro = bt.Cerebro(optreturn=False)

In [135]:
data = bt.feeds.YahooFinanceCSVData(dataname='Test.csv')

In [136]:
cerebro.adddata(data)

In [137]:
#Add strategy to Cerebro
cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe_ratio')
cerebro.optstrategy(MAcrossover, pfast=range(5, 20), pslow=range(50, 100))  

#Default position size
cerebro.addsizer(bt.sizers.SizerFix, stake=3)

In [139]:
cerebro.run()

[]

In [138]:
optimized_runs = cerebro.run()

final_results_list = []
for run in optimized_runs:
    for strategy in run:
        PnL = round(strategy.broker.get_value() - 10000,2)
        sharpe = strategy.analyzers.sharpe_ratio.get_analysis()
        final_results_list.append([strategy.params.pfast, 
            strategy.params.pslow, PnL, sharpe['sharperatio']])

sort_by_sharpe = sorted(final_results_list, key=lambda x: x[3], 
                         reverse=True)
for line in sort_by_sharpe[:5]:
    print(line)

Process SpawnPoolWorker-3:
Process SpawnPoolWorker-9:
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-7:
Process SpawnPoolWorker-6:
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-5:
Process SpawnPoolWorker-8:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-12:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-11:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-14:
Process SpawnPoolWorker-13:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-15:
Process SpawnPoolWorker-17:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker

    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-16:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-20:
Process SpawnPoolWorker-19:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-21:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-18:
Process SpawnPoolWorker-23:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-22:
Traceback (most recent call last):
Process SpawnPoolWorker-24:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-25:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-26:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-27:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-28:
Process SpawnPoolWorker-30:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-29:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-33:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-34:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-32:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-35:
Process SpawnPoolWorker-31:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-36:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-39:
Process SpawnPoolWorker-41:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-38:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
Process SpawnPoolWorker-42:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-37:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-43:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-40:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-44:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-46:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-45:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-47:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-48:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-50:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-49:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-52:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-57:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-54:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-58:
Process SpawnPoolWorker-51:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-55:
Process SpawnPoolWorker-53:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-56:
Process SpawnPoolWorker-59:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-60:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-62:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-66:
Process SpawnPoolWorker-61:
Process SpawnPoolWorker-63:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-64:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-67:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-65:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-69:
Process SpawnPoolWorker-68:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-70:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-72:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-71:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-74:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-73:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-75:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-76:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-78:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-77:
Process SpawnPoolWorker-80:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-79:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-81:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-82:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-83:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-84:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-85:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-87:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-86:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-88:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-92:
Process SpawnPoolWorker-89:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-93:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-91:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-94:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-95:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-96:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-90:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-99:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-100:
Process SpawnPoolWorker-98:
Process SpawnPoolWorker-101:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-97:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-103:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-104:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-102:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-105:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-107:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-108:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-106:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-113:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-110:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-109:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-111:
Process SpawnPoolWorker-114:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-112:
Process SpawnPoolWorker-115:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-118:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-117:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-119:
Process SpawnPoolWorker-116:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-120:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-122:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-121:
Process SpawnPoolWorker-123:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-125:
Process SpawnPoolWorker-124:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-129:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-127:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-128:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-126:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-130:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-132:
Process SpawnPoolWorker-131:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-133:
Process SpawnPoolWorker-137:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-135:
Traceback (most recent call last):
Process SpawnPoolWorker-134:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-136:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-138:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-139:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-140:
Process SpawnPoolWorker-141:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-142:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-144:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-143:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-146:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-145:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-147:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-148:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-151:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-149:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-150:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-152:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-153:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-154:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-155:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-156:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-158:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-157:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-161:
Process SpawnPoolWorker-160:
Process SpawnPoolWorker-159:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()

  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-162:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-163:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-164:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-165:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-166:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-167:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-168:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-169:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-170:
Process SpawnPoolWorker-173:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-172:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-171:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-175:
Process SpawnPoolWorker-174:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-177:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-176:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-178:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-179:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-180:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-181:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-182:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-184:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-183:
Process SpawnPoolWorker-185:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-187:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-186:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-188:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-189:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-190:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-191:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-192:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-193:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-194:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-196:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-197:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-198:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-195:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-199:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-200:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-201:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-202:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-203:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-204:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-205:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-206:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-207:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-208:
Process SpawnPoolWorker-209:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-210:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-212:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-211:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-213:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-214:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-215:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-216:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-217:
Process SpawnPoolWorker-218:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-219:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-220:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-221:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-222:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-223:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-224:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-225:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-226:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-227:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-228:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-229:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-231:
Process SpawnPoolWorker-230:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-233:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-232:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-235:
Process SpawnPoolWorker-236:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-234:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-237:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-238:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-239:
Process SpawnPoolWorker-240:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-242:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-241:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-244:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-243:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-246:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-245:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-247:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-249:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-248:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-250:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-251:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-252:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-253:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-256:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-254:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-255:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-257:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-258:
Process SpawnPoolWorker-260:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-259:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-261:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-262:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-264:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-263:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-265:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-267:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-266:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-269:
Process SpawnPoolWorker-268:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-271:
Process SpawnPoolWorker-270:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-273:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-272:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-274:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-275:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-276:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-277:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-278:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-279:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-280:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-281:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-284:
Process SpawnPoolWorker-283:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-285:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-282:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-286:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-287:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-288:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-289:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-291:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-290:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-292:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-295:
Process SpawnPoolWorker-293:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-294:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-296:
Process SpawnPoolWorker-297:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
Traceback (most recent call last):
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-298:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-299:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-300:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-302:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-304:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-303:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-301:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-305:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-306:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-309:
Process SpawnPoolWorker-307:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-308:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-310:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-311:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-312:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()

  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-313:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-314:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-315:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-318:
Process SpawnPoolWorker-317:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-316:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-319:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-320:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-321:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-322:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-323:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-324:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-325:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-328:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-326:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-327:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-329:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-330:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-331:
Process SpawnPoolWorker-332:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-333:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-334:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-335:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-336:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-338:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-337:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-341:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-339:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-340:
Process SpawnPoolWorker-342:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
Process SpawnPoolWorker-343:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-344:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-345:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-346:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-348:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-347:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-351:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-349:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-350:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-352:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-353:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-354:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-356:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-355:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-357:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-358:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-359:
Process SpawnPoolWorker-360:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-361:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-362:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-363:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-364:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-365:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-366:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-367:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-368:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-369:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-370:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-372:
Process SpawnPoolWorker-373:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-371:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-374:
Process SpawnPoolWorker-375:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-376:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-377:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-378:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-379:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-380:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-381:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-382:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-383:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-384:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-385:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-386:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-387:
Process SpawnPoolWorker-389:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-388:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-390:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-391:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-392:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-393:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-394:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-395:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-396:
Process SpawnPoolWorker-397:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-398:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-400:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-399:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-401:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-402:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-403:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-404:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-405:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-406:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-407:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-410:
Process SpawnPoolWorker-411:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-408:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-409:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-412:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-413:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-414:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-415:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-417:
Process SpawnPoolWorker-416:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-418:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-419:
Process SpawnPoolWorker-420:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-421:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-422:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-423:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-424:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-425:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-426:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-427:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-428:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-429:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-431:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-430:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-432:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-433:
Process SpawnPoolWorker-434:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()

Process SpawnPoolWorker-442:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-444:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-443:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-445:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-446:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-447:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-448:
Process SpawnPoolWorker-449:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-450:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-451:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-452:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-453:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-456:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-454:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-455:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-457:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-458:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-460:
Process SpawnPoolWorker-459:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-461:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-462:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-463:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-464:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-465:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-466:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-468:
Process SpawnPoolWorker-467:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-469:
Process SpawnPoolWorker-470:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-471:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-472:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-473:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-474:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-475:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-476:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-477:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-478:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-479:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-480:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-481:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-482:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-483:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-484:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-485:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-486:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-487:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-488:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-489:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-491:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-492:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-490:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-493:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-494:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-495:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-496:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-497:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-498:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-499:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-500:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-501:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-503:
Process SpawnPoolWorker-502:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-504:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-505:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-506:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-507:
Process SpawnPoolWorker-508:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-509:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-510:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-511:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-512:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-513:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-516:
Process SpawnPoolWorker-515:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-514:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-517:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-518:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-519:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-520:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-521:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-522:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-523:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-524:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-525:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-526:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-528:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-527:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-530:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-531:
Process SpawnPoolWorker-529:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-532:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-533:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-534:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-535:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-536:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-537:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)

AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-538:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-539:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-542:
Process SpawnPoolWorker-540:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-541:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-543:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Process SpawnPoolWorker-544:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-545:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-546:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-547:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-548:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-549:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-550:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-551:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-553:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-552:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-554:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-555:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-556:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-557:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-558:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-559:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-560:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-561:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-563:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-562:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-564:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-566:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process SpawnPoolWorker-565:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-567:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-568:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-569:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-570:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-571:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-572:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-573:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-575:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-574:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-577:
Process SpawnPoolWorker-576:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-578:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-579:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-580:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-581:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-582:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-583:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-585:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-584:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-586:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-587:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-588:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-590:
Process SpawnPoolWorker-589:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-591:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-592:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-593:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-594:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-595:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-596:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-597:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-598:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-599:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-600:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-601:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-602:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-603:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-604:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-605:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-606:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-607:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-609:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-608:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-613:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-610:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-611:
Process SpawnPoolWorker-612:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-614:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-615:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-616:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-617:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-618:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-619:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-620:
Process SpawnPoolWorker-621:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-623:
Process SpawnPoolWorker-622:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-624:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-625:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-626:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-627:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-628:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-629:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-630:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-631:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-632:
Process SpawnPoolWorker-634:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
Process SpawnPoolWorker-633:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-635:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-636:
Process SpawnPoolWorker-638:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-637:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-640:
Process SpawnPoolWorker-639:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-641:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-642:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-643:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-644:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-647:
Process SpawnPoolWorker-645:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-648:
Process SpawnPoolWorker-646:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-649:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-650:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-651:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-652:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-653:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-654:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-655:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-656:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-657:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-658:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-659:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-660:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-661:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-662:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-663:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-664:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>

Process SpawnPoolWorker-665:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-666:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-667:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-668:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-670:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-669:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-671:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-672:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-673:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-674:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-675:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-676:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-677:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-678:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-679:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-680:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-681:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-682:
Process SpawnPoolWorker-683:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-684:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-685:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-686:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-687:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-688:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-689:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-690:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-691:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-693:
Process SpawnPoolWorker-692:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-694:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-695:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-696:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-697:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-698:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-699:
Traceback (most recent call last):

  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-700:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-701:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-702:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-703:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-704:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-705:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-706:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-707:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-708:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-709:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-710:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-711:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-712:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-713:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-714:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-715:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-716:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)

AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-717:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-718:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-720:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-719:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-721:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-722:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-723:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-724:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-725:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-726:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-727:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-729:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-728:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-730:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-731:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-732:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-733:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-734:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-735:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-736:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-737:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-738:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-739:
Process SpawnPoolWorker-740:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-741:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-742:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-743:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-744:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-745:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-746:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-747:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-748:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-749:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-750:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MAcrossover' on <module '__main__' (built-in)>
Process SpawnPoolWorker-762:
Process SpawnPoolWorker-761:
Process SpawnPoolWorker-760:
Process SpawnPoolWorker-759:
Process SpawnPoolWorker-758:
Process SpawnPoolWorker-757:
Process SpawnPoolWorker-756:
Process SpawnPoolWorker-755:
Process SpawnPoolWorker-754:
Process SpawnPoolWorker-753:
Process SpawnPoolWorker-752:
Process SpawnPoolWorker-751:
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
KeyboardInterrupt
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
KeyboardInterrupt
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/queues.py", line 365, in get
    res = self._reader.recv_bytes()
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/qingbin.zhuang/opt/anaconda3/envs/env39/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

KeyboardInterrupt:

In [2]:
import backtrader as bt

In [3]:
class MyStrategy(bt.Strategy):
    def next(self):
        pass

In [4]:
cerebro = bt.Cerebro()

In [5]:
cerebro.addstrategy(MyStrategy)
cerebro.run()

[]

In [12]:
data = bt.feeds.YahooFinanceCSVData(
    dataname='TSLA.csv',
    fromdate=datetime.datetime(2022, 11, 1),
    todate=datetime.datetime(2022, 12, 1),
)

In [29]:
data = bt.feeds.YahooFinanceCSVData(dataname='Test.csv')

In [71]:
class PrintClose(bt.Strategy):

    def __init__(self):
        #Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close
        

    def log(self, txt, dt=None):
        dt = dt or self.datas[0].datetime.date(0)
        print(f'{dt.isoformat()} {txt}') #Print date and close

    def next(self):
        self.log('Close: %.2f | %.2f | %.2f | %.2f |' % 
                 (self.dataclose[0], self.dataclose[1], self.dataclose[2], self.dataclose[3]))

#Instantiate Cerebro engine
cerebro = bt.Cerebro()

In [72]:
data = bt.feeds.YahooFinanceCSVData(dataname='AAPL.csv')

cerebro.adddata(data)

In [74]:
cerebro.addstrategy(PrintClose)

0

In [87]:
data[0]

140.94

In [75]:
cerebro.run()

[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-13 Close: 174.73 | 173.32 | 178.27 | 171.27 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-14 Close: 173.32 | 178.27 | 171.27 | 170.15 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-15 Close: 178.27 | 171.27 | 170.15 | 168.77 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-16 Close: 171.27 | 170.15 | 168.77 | 171.99 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-17 Close: 170.15 | 168.77 | 171.99 | 174.63 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-20 Close: 168.77 | 171.99 | 174.63 | 175.26 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-21 Close: 171.99 | 174.63 | 175.26 | 179.29 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-22 Close: 174.63 | 175.26 | 179.29 | 178.26 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-23 Close: 175.26 | 179.29 | 178.26 | 178.34 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-27 Close: 179.29 | 178.26 | 178.34 | 177.17 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-28 Close: 178.26 | 178.34 | 177.17 | 176.55 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-29 Close: 178.34 | 177.17 | 176.55 | 180.96 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-30 Close: 177.17 | 176.55 | 180.96 | 178.66 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2021-12-31 Close: 176.55 | 180.96 | 178.66 | 173.91 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-03 Close: 180.96 | 178.66 | 173.91 | 171.01 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-04 Close: 178.66 | 173.91 | 171.01 | 171.18 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-05 Close: 173.91 | 171.01 | 171.18 | 171.20 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-06 Close: 171.01 | 171.18 | 171.20 | 174.07 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-07 Close: 171.18 | 171.20 | 174.07 | 174.52 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-10 Close: 171.20 | 174.07 | 174.52 | 171.20 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-11 Close: 174.07 | 174.52 | 171.20 | 172.07 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-12 Close: 174.52 | 171.20 | 172.07 | 168.82 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-13 Close: 171.20 | 172.07 | 168.82 | 165.27 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-14 Close: 172.07 | 168.82 | 165.27 | 163.56 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-18 Close: 168.82 | 165.27 | 163.56 | 161.47 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-19 Close: 165.27 | 163.56 | 161.47 | 160.69 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-20 Close: 163.56 | 161.47 | 160.69 | 158.86 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-21 Close: 161.47 | 160.69 | 158.86 | 158.77 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-24 Close: 160.69 | 158.86 | 158.77 | 158.30 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-25 Close: 158.86 | 158.77 | 158.30 | 169.35 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-26 Close: 158.77 | 158.30 | 169.35 | 173.77 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-27 Close: 158.30 | 169.35 | 173.77 | 173.60 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-28 Close: 169.35 | 173.77 | 173.60 | 174.83 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-01-31 Close: 173.77 | 173.60 | 174.83 | 171.90 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-01 Close: 173.60 | 174.83 | 171.90 | 171.61 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-02 Close: 174.83 | 171.90 | 171.61 | 170.89 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-03 Close: 171.90 | 171.61 | 170.89 | 174.04 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-04 Close: 171.61 | 170.89 | 174.04 | 175.49 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-07 Close: 170.89 | 174.04 | 175.49 | 171.34 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-08 Close: 174.04 | 175.49 | 171.34 | 167.88 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-09 Close: 175.49 | 171.34 | 167.88 | 168.12 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-10 Close: 171.34 | 167.88 | 168.12 | 172.01 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-11 Close: 167.88 | 168.12 | 172.01 | 171.77 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-14 Close: 168.12 | 172.01 | 171.77 | 168.12 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-15 Close: 172.01 | 171.77 | 168.12 | 166.55 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-16 Close: 171.77 | 168.12 | 166.55 | 163.58 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-17 Close: 168.12 | 166.55 | 163.58 | 159.35 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-18 Close: 166.55 | 163.58 | 159.35 | 162.01 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-22 Close: 163.58 | 159.35 | 162.01 | 164.11 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-23 Close: 159.35 | 162.01 | 164.11 | 164.38 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-24 Close: 162.01 | 164.11 | 164.38 | 162.47 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-25 Close: 164.11 | 164.38 | 162.47 | 165.81 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-02-28 Close: 164.38 | 162.47 | 165.81 | 165.48 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-01 Close: 162.47 | 165.81 | 165.48 | 162.44 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-02 Close: 165.81 | 165.48 | 162.44 | 158.58 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-03 Close: 165.48 | 162.44 | 158.58 | 156.73 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-04 Close: 162.44 | 158.58 | 156.73 | 162.22 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-07 Close: 158.58 | 156.73 | 162.22 | 157.81 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-08 Close: 156.73 | 162.22 | 157.81 | 154.03 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-09 Close: 162.22 | 157.81 | 154.03 | 149.94 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-10 Close: 157.81 | 154.03 | 149.94 | 154.39 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-11 Close: 154.03 | 149.94 | 154.39 | 158.87 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-14 Close: 149.94 | 154.39 | 158.87 | 159.90 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-15 Close: 154.39 | 158.87 | 159.90 | 163.24 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-16 Close: 158.87 | 159.90 | 163.24 | 164.64 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-17 Close: 159.90 | 163.24 | 164.64 | 168.06 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-18 Close: 163.24 | 164.64 | 168.06 | 169.44 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-21 Close: 164.64 | 168.06 | 169.44 | 173.29 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-22 Close: 168.06 | 169.44 | 173.29 | 173.93 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-23 Close: 169.44 | 173.29 | 173.93 | 174.81 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-24 Close: 173.29 | 173.93 | 174.81 | 178.15 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-25 Close: 173.93 | 174.81 | 178.15 | 176.97 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-28 Close: 174.81 | 178.15 | 176.97 | 173.82 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-29 Close: 178.15 | 176.97 | 173.82 | 173.52 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-30 Close: 176.97 | 173.82 | 173.52 | 177.64 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-03-31 Close: 173.82 | 173.52 | 177.64 | 174.27 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-01 Close: 173.52 | 177.64 | 174.27 | 171.06 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-04 Close: 177.64 | 174.27 | 171.06 | 171.36 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-05 Close: 174.27 | 171.06 | 171.36 | 169.32 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-06 Close: 171.06 | 171.36 | 169.32 | 165.00 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-07 Close: 171.36 | 169.32 | 165.00 | 166.90 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-08 Close: 169.32 | 165.00 | 166.90 | 169.63 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-11 Close: 165.00 | 166.90 | 169.63 | 164.55 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-12 Close: 166.90 | 169.63 | 164.55 | 164.33 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-13 Close: 169.63 | 164.55 | 164.33 | 166.65 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-14 Close: 164.55 | 164.33 | 166.65 | 166.48 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-18 Close: 164.33 | 166.65 | 166.48 | 165.67 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-19 Close: 166.65 | 166.48 | 165.67 | 161.06 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-20 Close: 166.48 | 165.67 | 161.06 | 162.15 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-21 Close: 165.67 | 161.06 | 162.15 | 156.09 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-22 Close: 161.06 | 162.15 | 156.09 | 155.86 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-25 Close: 162.15 | 156.09 | 155.86 | 162.90 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-26 Close: 156.09 | 155.86 | 162.90 | 156.94 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-27 Close: 155.86 | 162.90 | 156.94 | 157.25 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-28 Close: 162.90 | 156.94 | 157.25 | 158.76 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-04-29 Close: 156.94 | 157.25 | 158.76 | 165.27 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-02 Close: 157.25 | 158.76 | 165.27 | 156.06 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-03 Close: 158.76 | 165.27 | 156.06 | 156.80 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-04 Close: 165.27 | 156.06 | 156.80 | 151.60 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-05 Close: 156.06 | 156.80 | 151.60 | 154.04 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-06 Close: 156.80 | 151.60 | 154.04 | 146.05 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-09 Close: 151.60 | 154.04 | 146.05 | 142.13 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-10 Close: 154.04 | 146.05 | 142.13 | 146.66 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-11 Close: 146.05 | 142.13 | 146.66 | 145.10 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-12 Close: 142.13 | 146.66 | 145.10 | 148.79 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-13 Close: 146.66 | 145.10 | 148.79 | 140.39 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-16 Close: 145.10 | 148.79 | 140.39 | 136.93 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-17 Close: 148.79 | 140.39 | 136.93 | 137.17 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-18 Close: 140.39 | 136.93 | 137.17 | 142.67 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-19 Close: 136.93 | 137.17 | 142.67 | 139.93 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-20 Close: 137.17 | 142.67 | 139.93 | 140.09 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-23 Close: 142.67 | 139.93 | 140.09 | 143.34 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-24 Close: 139.93 | 140.09 | 143.34 | 149.18 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-25 Close: 140.09 | 143.34 | 149.18 | 148.39 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-26 Close: 143.34 | 149.18 | 148.39 | 148.26 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-27 Close: 149.18 | 148.39 | 148.26 | 150.75 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-05-31 Close: 148.39 | 148.26 | 150.75 | 144.94 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-01 Close: 148.26 | 150.75 | 144.94 | 145.70 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-02 Close: 150.75 | 144.94 | 145.70 | 148.26 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-03 Close: 144.94 | 145.70 | 148.26 | 147.51 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-06 Close: 145.70 | 148.26 | 147.51 | 142.21 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-07 Close: 148.26 | 147.51 | 142.21 | 136.71 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-08 Close: 147.51 | 142.21 | 136.71 | 131.48 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-09 Close: 142.21 | 136.71 | 131.48 | 132.36 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-10 Close: 136.71 | 131.48 | 132.36 | 135.02 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-13 Close: 131.48 | 132.36 | 135.02 | 129.66 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-14 Close: 132.36 | 135.02 | 129.66 | 131.16 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-15 Close: 135.02 | 129.66 | 131.16 | 135.46 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-16 Close: 129.66 | 131.16 | 135.46 | 134.94 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-17 Close: 131.16 | 135.46 | 134.94 | 137.85 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-21 Close: 135.46 | 134.94 | 137.85 | 141.23 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-22 Close: 134.94 | 137.85 | 141.23 | 141.23 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-23 Close: 137.85 | 141.23 | 141.23 | 137.02 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-24 Close: 141.23 | 141.23 | 137.02 | 138.81 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-27 Close: 141.23 | 137.02 | 138.81 | 136.30 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-28 Close: 137.02 | 138.81 | 136.30 | 138.51 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-29 Close: 138.81 | 136.30 | 138.51 | 141.13 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-06-30 Close: 136.30 | 138.51 | 141.13 | 142.49 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-01 Close: 138.51 | 141.13 | 142.49 | 145.90 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-05 Close: 141.13 | 142.49 | 145.90 | 146.59 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-06 Close: 142.49 | 145.90 | 146.59 | 144.43 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-07 Close: 145.90 | 146.59 | 144.43 | 145.42 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-08 Close: 146.59 | 144.43 | 145.42 | 145.05 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-11 Close: 144.43 | 145.42 | 145.05 | 148.02 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-12 Close: 145.42 | 145.05 | 148.02 | 149.71 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-13 Close: 145.05 | 148.02 | 149.71 | 146.62 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-14 Close: 148.02 | 149.71 | 146.62 | 150.54 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-15 Close: 149.71 | 146.62 | 150.54 | 152.57 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-18 Close: 146.62 | 150.54 | 152.57 | 154.88 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-19 Close: 150.54 | 152.57 | 154.88 | 153.62 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-20 Close: 152.57 | 154.88 | 153.62 | 152.48 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-21 Close: 154.88 | 153.62 | 152.48 | 151.14 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-22 Close: 153.62 | 152.48 | 151.14 | 156.31 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-25 Close: 152.48 | 151.14 | 156.31 | 156.87 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-26 Close: 151.14 | 156.31 | 156.87 | 162.02 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-27 Close: 156.31 | 156.87 | 162.02 | 161.02 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-28 Close: 156.87 | 162.02 | 161.02 | 159.52 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]
2022-07-29 Close: 162.02 | 161.02 | 159.52 | 165.62 |
[<backtrader.feeds.yahoo.YahooFinanceCSVData object at 0x7fbcd4238730>]

IndexError: array index out of range

In [25]:
from yahoo_fin.stock_info import get_data

In [65]:
amazon_weekly= get_data("amzn", start_date="10/04/2022", end_date="12/04/2022", interval="1wk")

In [66]:
amazon_weekly

,open,high,low,close,adjclose,volume,ticker
2022-10-03,113.580002,123.000000,112.449997,114.559998,114.559998,258903800,AMZN
2022-10-10,115.099998,116.250000,105.349998,106.900002,106.900002,299106000,AMZN
2022-10-17,110.110001,119.589996,110.089996,119.320000,119.320000,280043100,AMZN
2022-10-24,119.980003,121.320000,97.660004,103.410004,103.410004,522007200,AMZN
2022-10-31,103.559998,104.870003,88.040001,90.980003,90.980003,654167800,AMZN
2022-11-07,91.949997,101.190002,85.870003,100.790001,100.790001,542000700,AMZN
2022-11-14,98.769997,103.790001,92.480003,94.139999,94.139999,453874300,AMZN
2022-11-21,93.970001,95.019997,90.589996,93.410004,93.410004,241025600,AMZN
2022-11-28,93.930000,97.230003,91.440002,94.129997,94.129997,384053600,AMZN

In [28]:
amazon_weekly.to_csv("Test.csv")

In [114]:
df = pd.read_csv("/Users/qingbin.zhuang/Downloads/flink_job_3dims_gb_version_20221214-094448.csv")

In [123]:
pd.Series([1,2],index=['f','gg'])

f     1
gg    2
dtype: int64

In [124]:
def t(data):
    return (data['auc'] * data['pv']).sum() / data['pv'].sum()

def tmax(data):
    return pd.Series([data['auc'].mean(), 
        (data['auc'] * data['pv']).sum() / data['pv'].sum(), 
        data[data['pv'] == data['pv'].max()]['auc'].values[0]],
        index = ['mean', 'weight', 'max_pv'])

In [131]:

print("datetime\tmean\tweight\tmax_pv")
for _, row in df.groupby('datetime').apply(tmax).reset_index().iterrows():
    print(f'{row["datetime"]}\t{row["mean"]}\t{row["weight"]}\t{row["max_pv"]}')

datetime	mean	weight	max_pv
2022-12-12/00	0.692599	0.692599	0.692599
2022-12-12/01	0.696047	0.696047	0.696047
2022-12-12/02	0.697488	0.697488	0.697488
2022-12-12/03	0.704054	0.704054	0.704054
2022-12-12/04	0.712393	0.712393	0.712393
2022-12-12/05	0.709528	0.709528	0.709528
2022-12-12/06	0.707647	0.707647	0.707647
2022-12-12/07	0.699978	0.6999780000000001	0.699978
2022-12-12/08	0.708651	0.708651	0.708651
2022-12-12/09	0.709947	0.7104690071778583	0.713121
2022-12-12/10	0.6181785	0.7091678670975634	0.709622
2022-12-12/11	0.712827	0.7128270000000001	0.712827
2022-12-12/12	0.713846	0.7138460000000001	0.713846
2022-12-12/13	0.71374	0.7137400000000002	0.71374
2022-12-12/14	0.717905	0.717905	0.717905
2022-12-12/15	0.716638	0.7166380000000001	0.716638
2022-12-12/16	0.71862	0.7186200000000001	0.71862
2022-12-12/17	0.71368	0.71368	0.71368
2022-12-12/18	0.7077	0.7077000000000001	0.7077
2022-12-12/19	0.713823	0.7138230000000001	0.713823
2022-12-12/20	0.714306	0.714306	0.714306
2022-12-12/21	0.711303	0.711303	0.711303
2022-12-12/22	0.704416	0.704416	0.704416
2022-12-12/23	0.699005	0.699005	0.699005
2022-12-13/00	0.701125	0.7011250000000001	0.701125
2022-12-13/01	0.700543	0.700543	0.700543
2022-12-13/02	0.704706	0.704706	0.704706
2022-12-13/03	0.710289	0.710289	0.710289
2022-12-13/04	0.72449	0.72449	0.72449
2022-12-13/05	0.716027	0.716027	0.716027
2022-12-13/06	0.709678	0.7096780000000001	0.709678
2022-12-13/07	0.702824	0.702824	0.702824
2022-12-13/08	0.701873	0.701873	0.701873
2022-12-13/09	0.706351	0.705349488678714	0.703697
2022-12-13/10	0.7047844999999999	0.708892823217504	0.70893
2022-12-13/11	0.71638	0.71638	0.71638
2022-12-13/12	0.715561	0.715561	0.715561
2022-12-13/13	0.711343	0.711343	0.711343

In [126]:
df.groupby('datetime').apply(t).reset_index().0

SyntaxError: invalid syntax (791809473.py, line 1)

In [107]:
df[df['pv'] == df['pv'].max]

Empty DataFrame
Columns: [datetime, dt, hour, group_name, ranker_version, uv, pv, n_pos, n_neg, auc, uauc, wuauc]
Index: []

In [109]:
df['pv'].max()

2025127