In [1]:
import matplotlib
matplotlib.use('module://matplotlib_inline.backend_inline')
import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
import backtrader as bt
import backtrader.indicators as btind # 导入策略分析模块
import pandas as pd
import tushare as ts
import warnings
import datetime
warnings.filterwarnings("ignore")

In [2]:
# 引入自己开发的模块
from pathlib import Path
import sys
root = Path.cwd()
if not (root / 'common').exists():      # 如果当前目录没有 common/
    sys.path.insert(0, str(root.parent))  # 把父目录放到 import 路径最前

from common.utils import get_engine
from DataFetch.stock_basic import *

### 从本地mysql取数据

In [3]:
engine = get_engine()

In [4]:

ts_code = '000001.SZ'
query = f"""
SELECT * FROM daily_kline
WHERE ts_code = '{ts_code}'
ORDER BY trade_date ASC
"""
df_sql1 = pd.read_sql(query, engine)
df_sql1['date'] = pd.to_datetime(df_sql1['trade_date'])

In [5]:
ts_code = '002594.SZ'
query = f"""
SELECT * FROM daily_kline
WHERE ts_code = '{ts_code}'
ORDER BY trade_date ASC
"""
df_sql2 = pd.read_sql(query, engine)
df_sql2['date'] = pd.to_datetime(df_sql2['trade_date'])

### 从tushare取数据

In [6]:
# from DataFetch.stock_basic import *

In [7]:
# stock_daily = StockDailyFetch()
# stock_daily.fetch_data(name = "000001.SZ 数据", ts_code="000001.SZ", start_date="20100901", end_date = "20101230")
# df_ts000001 = stock_daily.data
# df_ts000001['date'] = pd.to_datetime(df_ts000001['trade_date'])

In [8]:
# stock_daily = StockDailyFetch()
# stock_daily.fetch_data(name = "600519.SH 数据", ts_code="600519.SH", start_date="20100901", end_date = "20101230")
# df_ts600519 = stock_daily.data
# df_ts600519['date'] = pd.to_datetime(df_ts600519['trade_date'])

## 简单策略demo

In [9]:
class TS_Data(bt.feeds.PandasData):
    # 要添加的线 (初始 'close', 'low', 'high', 'open', 'volume', 'openinterest', 'datetime')
    lines = ('pre_close', 'change', 'amount', 'extra') 
    # 设置 line 在数据源上的列位置
    # -1 表示自动按列名匹配数据, None表示不存在（datetime则表示在index）, string直接写数据中的列名
    params = (
        ('fromdate', datetime.datetime(2022,4,1)),
        ('todate', datetime.datetime(2022,8,8)),
        ('nullvalue', 0.0),
        ('dtformat', ('%Y-%m-%d')),
        ('datetime', "date"),
        ('open', "open"),
        ('high', "high"),
        ('low', "low"),
        ('close', "close"),
        ('pre_close', "pre_close"),
        ('change', "change"),
        ('openinterest', "pct_chg"),
        ('volume', "vol"),
        ('amount', "amount"),
        ('extra', -1)
    )
    # def _load(self):
    #     # 调用原始的 _load 方法
    #     super()._load()

    #     # 添加你的自定义逻辑
    #     # _load方法是在每一个数据点被加载时调用的，所以你可以在这里添加你的自定义逻辑。
    #     # 你可以访问self.p.dataname来获取原始的Pandas DataFrame，然后从中提取你需要的数据。
    #     self.lines.extra[0] = self.p.dataname['extra'][self._idx]

    #     return True

In [10]:
class StockCommission(bt.CommInfoBase):
    params = (
        ('stocklike', True), # 指定为股票模式
        ('commtype', bt.CommInfoBase.COMM_PERC), # 使用百分比费用模式
        ('percabs', True), # commission 不以 % 为单位
        ('stamp_duty', 0.001), # 印花税默认为 0.1%
        ('commission', 0.0001), # 交易佣金默认为 0.01%
     ) 
    
    # 自定义费用计算公式
    def _getcommission(self, size, price, pseudoexec):
        if size > 0: # 买入时，只考虑佣金
            return abs(size) * price * self.p.commission
        elif size < 0: # 卖出时，同时考虑佣金和印花税
            return abs(size) * price * (self.p.commission + self.p.stamp_duty)
        else:
            return 0

In [11]:
# 初始化 交易
cerebro = bt.Cerebro()
# 设置初始资金
cerebro.broker.setcash(50000.0)
cerebro.broker.getcash() # 获取当前可用资金

# 设置交易费用
comminfo = StockCommission()                   
cerebro.broker.addcommissioninfo(comminfo)

# 通过调用 brokers 的 set_slippage_perc 方法设置百分比滑点
cerebro.broker.set_slippage_perc(perc=0.0001)



# data_ts_600519 = TS_Data(dataname=df_ts600519, fromdate=datetime.datetime(2010,9,1),
#                 todate=datetime.datetime(2010,12,30), nullvalue = None)
# data_ts_000001 = TS_Data(dataname=df_ts000001, fromdate=datetime.datetime(2010,9,1),
#                 todate=datetime.datetime(2010,12,30), nullvalue = None)

data_sql1 = TS_Data(dataname=df_sql1, fromdate=datetime.datetime(2025,1,1),todate=datetime.datetime(2025,8,8))
data_sql2 = TS_Data(dataname=df_sql2, fromdate=datetime.datetime(2025,1,1),todate=datetime.datetime(2025,8,8))
cerebro.adddata(data_sql1, name='000001')
cerebro.adddata(data_sql2, name='002594')

In [12]:


class TestStrategy(bt.Strategy):
    # self.data = self.datas[0]   self.dataX = self.datas[0]
    def __init__(self):
        self.dec = "="*8
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 self 策略本身的 lines"))
        print(self.lines.getlinealiases())
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 self.datas 第一个数据表格的 lines"))
        print(self.datas[0].lines.getlinealiases())
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 最后一天数据"))

        me1 = btind.EMA(self.datas[0].close, period=3)

        # Add a MovingAverageSimple indicator
        self.sma = bt.indicators.SimpleMovingAverage(
            self.datas[0], period=5)

        # Indicators for the plotting show
        bt.indicators.ExponentialMovingAverage(self.datas[0], period=25)
        bt.indicators.WeightedMovingAverage(self.datas[0], period=25,
                                            subplot=True)
        bt.indicators.StochasticSlow(self.datas[0])
        bt.indicators.MACDHisto(self.datas[0])
        rsi = bt.indicators.RSI(self.datas[0])
        bt.indicators.SmoothedMovingAverage(rsi, period=10)
        bt.indicators.ATR(self.datas[0], plot=False)

        

    def prenext(self):
        print("prenext ", bt.num2date(self.datas[0].datetime[0]))

    def nextstart(self):
        
        print("nextstart ", bt.num2date(self.datas[0].datetime[0]))
        self.next()
    
    def next(self):
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 当天数据"))

        print("date: {}, data1 close: {:.2f}, data2 close: {:.2f}. ".format(
                bt.num2date(self.datas[0].datetime[0]), self.datas[0].close[0], self.datas[1].close[0]))
        print('seen:', len(self.data), ' / total:', self.data.buflen())
        print('seen:', len(self.datas[0].close), ' / total:', self.datas[0].close.buflen())
        # print(self.datas[0].close[-1], "\nself.datas[0].lines.close.get(ago=0, size=2)", self.datas[0].lines.close.get(ago=0, size=2), 
        #       "\nself.datas[0].lines.close.get(ago=1, size=2)", self.datas[0].lines.close.get(ago=1, size=2),
        #       "\nself.datas[0].lines.close.get(size=3)", self.datas[0].lines.close.get(size=3),
        #       "\nself.datas[0].lines.close.get(ago=-1,size=3)", self.datas[0].lines.close.get(ago=-1,size=3))

In [13]:
cerebro.addstrategy(TestStrategy)
cerebro.run()

========                打印 self 策略本身的 lines                 ========
('datetime',)
========            打印 self.datas 第一个数据表格的 lines            ========
('close', 'low', 'high', 'open', 'volume', 'openinterest', 'datetime', 'pre_close', 'change', 'amount', 'extra')
========                     打印 最后一天数据                      ========
prenext  2025-01-02 00:00:00
prenext  2025-01-03 00:00:00
prenext  2025-01-06 00:00:00
prenext  2025-01-07 00:00:00
prenext  2025-01-08 00:00:00
prenext  2025-01-09 00:00:00
prenext  2025-01-10 00:00:00
prenext  2025-01-13 00:00:00
prenext  2025-01-14 00:00:00
prenext  2025-01-15 00:00:00
prenext  2025-01-16 00:00:00
prenext  2025-01-17 00:00:00
prenext  2025-01-20 00:00:00
prenext  2025-01-21 00:00:00
prenext  2025-01-22 00:00:00
prenext  2025-01-23 00:00:00
prenext  2025-01-24 00:00:00
prenext  2025-01-27 00:00:00
prenext  2025-02-05 00:00:00
prenext  2025-02-06 00:00:00
prenext  2025-02-07 00:00:00
prenext  2025-02-10 00:00:00
prenext  2025-02-11 00:00:00
prenext  2025-02-12 00:00:00
prenext  2025-02-13 00:00:00
prenext  2025-02-14 00:00:00
prenext  2025-02-17 00:00:00
prenext  2025-02-18 00:00:00
prenext  2025-02-19 00:00:00
prenext  2025-02-20 00:00:00
prenext  2025-02-21 00:00:00
prenext  2025-02-24 00:00:00
prenext  2025-02-25 00:00:00
nextstart  2025-02-26 00:00:00
========                      打印 当天数据                       ========
date: 2025-02-26 00:00:00, data1 close: 11.52, data2 close: 372.10.
seen: 34  / total: 146
seen: 34  / total: 146
========                      打印 当天数据                       ========
date: 2025-02-27 00:00:00, data1 close: 11.62, data2 close: 375.50.
seen: 35  / total: 146
seen: 35  / total: 146
========                      打印 当天数据                       ========
date: 2025-02-28 00:00:00, data1 close: 11.53, data2 close: 361.82.
seen: 36  / total: 146
seen: 36  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-03 00:00:00, data1 close: 11.51, data2 close: 360.21.
seen: 37  / total: 146
seen: 37  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-04 00:00:00, data1 close: 11.51, data2 close: 344.84.
seen: 38  / total: 146
seen: 38  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-05 00:00:00, data1 close: 11.66, data2 close: 353.96.
seen: 39  / total: 146
seen: 39  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-06 00:00:00, data1 close: 11.63, data2 close: 358.93.
seen: 40  / total: 146
seen: 40  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-07 00:00:00, data1 close: 11.67, data2 close: 356.40.
seen: 41  / total: 146
seen: 41  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-10 00:00:00, data1 close: 11.59, data2 close: 351.00.
seen: 42  / total: 146
seen: 42  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-11 00:00:00, data1 close: 11.61, data2 close: 350.38.
seen: 43  / total: 146
seen: 43  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-12 00:00:00, data1 close: 11.85, data2 close: 351.00.
seen: 44  / total: 146
seen: 44  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-13 00:00:00, data1 close: 11.84, data2 close: 354.50.
seen: 45  / total: 146
seen: 45  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-14 00:00:00, data1 close: 11.97, data2 close: 375.94.
seen: 46  / total: 146
seen: 46  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-17 00:00:00, data1 close: 11.50, data2 close: 380.25.
seen: 47  / total: 146
seen: 47  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-18 00:00:00, data1 close: 11.49, data2 close: 384.57.
seen: 48  / total: 146
seen: 48  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-19 00:00:00, data1 close: 11.52, data2 close: 397.07.
seen: 49  / total: 146
seen: 49  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-20 00:00:00, data1 close: 11.49, data2 close: 399.99.
seen: 50  / total: 146
seen: 50  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-21 00:00:00, data1 close: 11.42, data2 close: 372.00.
seen: 51  / total: 146
seen: 51  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-24 00:00:00, data1 close: 11.38, data2 close: 375.36.
seen: 52  / total: 146
seen: 52  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-25 00:00:00, data1 close: 11.43, data2 close: 369.59.
seen: 53  / total: 146
seen: 53  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-26 00:00:00, data1 close: 11.38, data2 close: 376.01.
seen: 54  / total: 146
seen: 54  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-27 00:00:00, data1 close: 11.39, data2 close: 386.50.
seen: 55  / total: 146
seen: 55  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-28 00:00:00, data1 close: 11.35, data2 close: 382.50.
seen: 56  / total: 146
seen: 56  / total: 146
========                      打印 当天数据                       ========
date: 2025-03-31 00:00:00, data1 close: 11.26, data2 close: 374.90.
seen: 57  / total: 146
seen: 57  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-01 00:00:00, data1 close: 11.27, data2 close: 365.50.
seen: 58  / total: 146
seen: 58  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-02 00:00:00, data1 close: 11.37, data2 close: 360.50.
seen: 59  / total: 146
seen: 59  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-03 00:00:00, data1 close: 11.34, data2 close: 357.51.
seen: 60  / total: 146
seen: 60  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-07 00:00:00, data1 close: 10.70, data2 close: 321.76.
seen: 61  / total: 146
seen: 61  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-08 00:00:00, data1 close: 10.82, data2 close: 327.51.
seen: 62  / total: 146
seen: 62  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-09 00:00:00, data1 close: 10.80, data2 close: 324.60.
seen: 63  / total: 146
seen: 63  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-10 00:00:00, data1 close: 10.90, data2 close: 336.40.
seen: 64  / total: 146
seen: 64  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-11 00:00:00, data1 close: 10.89, data2 close: 354.98.
seen: 65  / total: 146
seen: 65  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-14 00:00:00, data1 close: 10.93, data2 close: 359.00.
seen: 66  / total: 146
seen: 66  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-15 00:00:00, data1 close: 10.95, data2 close: 359.97.
seen: 67  / total: 146
seen: 67  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-16 00:00:00, data1 close: 11.00, data2 close: 352.15.
seen: 68  / total: 146
seen: 68  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-17 00:00:00, data1 close: 11.06, data2 close: 349.68.
seen: 69  / total: 146
seen: 69  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-18 00:00:00, data1 close: 11.18, data2 close: 346.00.
seen: 70  / total: 146
seen: 70  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-21 00:00:00, data1 close: 11.02, data2 close: 348.76.
seen: 71  / total: 146
seen: 71  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-22 00:00:00, data1 close: 11.04, data2 close: 354.84.
seen: 72  / total: 146
seen: 72  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-23 00:00:00, data1 close: 11.01, data2 close: 371.99.
seen: 73  / total: 146
seen: 73  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-24 00:00:00, data1 close: 11.03, data2 close: 366.00.
seen: 74  / total: 146
seen: 74  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-25 00:00:00, data1 close: 11.01, data2 close: 370.83.
seen: 75  / total: 146
seen: 75  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-28 00:00:00, data1 close: 11.00, data2 close: 360.00.
seen: 76  / total: 146
seen: 76  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-29 00:00:00, data1 close: 10.98, data2 close: 355.00.
seen: 77  / total: 146
seen: 77  / total: 146
========                      打印 当天数据                       ========
date: 2025-04-30 00:00:00, data1 close: 10.91, data2 close: 353.09.
seen: 78  / total: 146
seen: 78  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-06 00:00:00, data1 close: 10.96, data2 close: 359.96.
seen: 79  / total: 146
seen: 79  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-07 00:00:00, data1 close: 11.03, data2 close: 359.20.
seen: 80  / total: 146
seen: 80  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-08 00:00:00, data1 close: 11.08, data2 close: 359.28.
seen: 81  / total: 146
seen: 81  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-09 00:00:00, data1 close: 11.15, data2 close: 363.22.
seen: 82  / total: 146
seen: 82  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-12 00:00:00, data1 close: 11.16, data2 close: 370.28.
seen: 83  / total: 146
seen: 83  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-13 00:00:00, data1 close: 11.29, data2 close: 366.50.
seen: 84  / total: 146
seen: 84  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-14 00:00:00, data1 close: 11.43, data2 close: 373.10.
seen: 85  / total: 146
seen: 85  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-15 00:00:00, data1 close: 11.39, data2 close: 376.80.
seen: 86  / total: 146
seen: 86  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-16 00:00:00, data1 close: 11.38, data2 close: 389.17.
seen: 87  / total: 146
seen: 87  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-19 00:00:00, data1 close: 11.37, data2 close: 382.81.
seen: 88  / total: 146
seen: 88  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-20 00:00:00, data1 close: 11.39, data2 close: 394.80.
seen: 89  / total: 146
seen: 89  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-21 00:00:00, data1 close: 11.48, data2 close: 400.00.
seen: 90  / total: 146
seen: 90  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-22 00:00:00, data1 close: 11.55, data2 close: 398.80.
seen: 91  / total: 146
seen: 91  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-23 00:00:00, data1 close: 11.46, data2 close: 405.00.
seen: 92  / total: 146
seen: 92  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-26 00:00:00, data1 close: 11.42, data2 close: 381.00.
seen: 93  / total: 146
seen: 93  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-27 00:00:00, data1 close: 11.49, data2 close: 372.41.
seen: 94  / total: 146
seen: 94  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-28 00:00:00, data1 close: 11.53, data2 close: 362.88.
seen: 95  / total: 146
seen: 95  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-29 00:00:00, data1 close: 11.46, data2 close: 361.13.
seen: 96  / total: 146
seen: 96  / total: 146
========                      打印 当天数据                       ========
date: 2025-05-30 00:00:00, data1 close: 11.56, data2 close: 352.30.
seen: 97  / total: 146
seen: 97  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-03 00:00:00, data1 close: 11.81, data2 close: 356.00.
seen: 98  / total: 146
seen: 98  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-04 00:00:00, data1 close: 11.84, data2 close: 360.52.
seen: 99  / total: 146
seen: 99  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-05 00:00:00, data1 close: 11.67, data2 close: 360.75.
seen: 100  / total: 146
seen: 100  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-06 00:00:00, data1 close: 11.70, data2 close: 359.96.
seen: 101  / total: 146
seen: 101  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-09 00:00:00, data1 close: 11.71, data2 close: 348.14.
seen: 102  / total: 146
seen: 102  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-10 00:00:00, data1 close: 11.81, data2 close: 353.13.
seen: 103  / total: 146
seen: 103  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-11 00:00:00, data1 close: 11.85, data2 close: 361.99.
seen: 104  / total: 146
seen: 104  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-12 00:00:00, data1 close: 11.68, data2 close: 353.24.
seen: 105  / total: 146
seen: 105  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-13 00:00:00, data1 close: 11.58, data2 close: 346.00.
seen: 106  / total: 146
seen: 106  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-16 00:00:00, data1 close: 11.79, data2 close: 344.43.
seen: 107  / total: 146
seen: 107  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-17 00:00:00, data1 close: 11.76, data2 close: 343.74.
seen: 108  / total: 146
seen: 108  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-18 00:00:00, data1 close: 11.77, data2 close: 346.95.
seen: 109  / total: 146
seen: 109  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-19 00:00:00, data1 close: 11.70, data2 close: 340.50.
seen: 110  / total: 146
seen: 110  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-20 00:00:00, data1 close: 11.84, data2 close: 340.25.
seen: 111  / total: 146
seen: 111  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-23 00:00:00, data1 close: 11.93, data2 close: 338.20.
seen: 112  / total: 146
seen: 112  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-24 00:00:00, data1 close: 11.93, data2 close: 343.38.
seen: 113  / total: 146
seen: 113  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-25 00:00:00, data1 close: 12.06, data2 close: 349.27.
seen: 114  / total: 146
seen: 114  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-26 00:00:00, data1 close: 12.41, data2 close: 337.44.
seen: 115  / total: 146
seen: 115  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-27 00:00:00, data1 close: 12.20, data2 close: 334.24.
seen: 116  / total: 146
seen: 116  / total: 146
========                      打印 当天数据                       ========
date: 2025-06-30 00:00:00, data1 close: 12.07, data2 close: 331.91.
seen: 117  / total: 146
seen: 117  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-01 00:00:00, data1 close: 12.30, data2 close: 331.34.
seen: 118  / total: 146
seen: 118  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-02 00:00:00, data1 close: 12.32, data2 close: 330.66.
seen: 119  / total: 146
seen: 119  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-03 00:00:00, data1 close: 12.35, data2 close: 334.56.
seen: 120  / total: 146
seen: 120  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-04 00:00:00, data1 close: 12.60, data2 close: 331.00.
seen: 121  / total: 146
seen: 121  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-07 00:00:00, data1 close: 12.78, data2 close: 328.59.
seen: 122  / total: 146
seen: 122  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-08 00:00:00, data1 close: 12.69, data2 close: 326.88.
seen: 123  / total: 146
seen: 123  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-09 00:00:00, data1 close: 12.84, data2 close: 325.80.
seen: 124  / total: 146
seen: 124  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-10 00:00:00, data1 close: 13.18, data2 close: 321.23.
seen: 125  / total: 146
seen: 125  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-11 00:00:00, data1 close: 12.91, data2 close: 323.91.
seen: 126  / total: 146
seen: 126  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-14 00:00:00, data1 close: 12.98, data2 close: 318.49.
seen: 127  / total: 146
seen: 127  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-15 00:00:00, data1 close: 12.73, data2 close: 323.05.
seen: 128  / total: 146
seen: 128  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-16 00:00:00, data1 close: 12.64, data2 close: 323.72.
seen: 129  / total: 146
seen: 129  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-17 00:00:00, data1 close: 12.59, data2 close: 328.02.
seen: 130  / total: 146
seen: 130  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-18 00:00:00, data1 close: 12.70, data2 close: 329.11.
seen: 131  / total: 146
seen: 131  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-21 00:00:00, data1 close: 12.61, data2 close: 334.12.
seen: 132  / total: 146
seen: 132  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-22 00:00:00, data1 close: 12.49, data2 close: 341.69.
seen: 133  / total: 146
seen: 133  / total: 146
========                      打印 当天数据                       ========
date: 2025-07-23 00:00:00, data1 close: 12.53, data2 close: 338.07.
seen: 134  / total: 146
seen: 134  / total: 146
========                      打印 当天数据                       ========

In [14]:
class My_MACD(bt.Indicator):
    lines = ('macd', 'signal', 'histo')
    params = (('period_me1',12),
              ('period_me2', 26),
              ('period_signal', 9),)

    def __init__(self):
        me1 = btind.EMA(self.datas[0].close, period=self.p.period_me1)
        me2 = btind.EMA(self.datas[0].close, period=self.p.period_me2)
        self.l.macd = me1 - me2
        self.l.signal = btind.EMA(self.l.macd, period=self.p.period_signal)
        self.l.histo = self.l.macd - self.l.signal

class TestStrategy1(bt.Strategy):
    # self.data = self.datas[0]   self.dataX = self.datas[0]
    def __init__(self):
        self.dec = "="*8
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 self 策略本身的 lines"))
        print(self.lines.getlinealiases())
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 self.datas 第一个数据表格的 lines"))
        print(self.datas[0].lines.getlinealiases())
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 最后一天数据"))
        print(bt.num2date(self.datas[0].datetime[0]), end = ':\t')
        print(self.datas[0].close[0], end = "\t")
        print(self.datas[0].openinterest[0])

        # 
        self.ma3 = btind.SimpleMovingAverage(self.datas[0].close, period=3)
        self.ma5 = btind.SimpleMovingAverage(self.datas[0].close, period=5)
        self.macd = My_MACD(period_me1=3,period_me2=5,period_signal=2)
        
    def next(self):
        print("{dec} {text:^50s} {dec}".format(dec=self.dec, text="打印 当天数据"))
        # print("date: {}, close: {:.2f}, ma3: {:.2f}, ma5: {:.2f}, macd: {:.2f}, signal: {:.2f}, histo: {:.2f}. ".format(
        #         bt.num2date(self.datas[0].datetime[0]), self.datas[0].close[0], self.ma3[0], self.ma5[0], 
        #         self.macd.macd[0], self.macd.signal[0], self.macd.histo[0]))
        print("date: {}, data1 close: {:.2f}, data2 close: {:.2f}. ".format(
                bt.num2date(self.datas[0].datetime[0]), self.datas[0].close[0], self.datas[1].close[0]))
        if self.ma5 > self.ma3:
            print("买买买")

In [15]:
# 初始化 交易
cerebro = bt.Cerebro()
# 设置初始资金
cerebro.broker.setcash(50000.0)
cerebro.broker.getcash() # 获取当前可用资金

# 设置交易费用
comminfo = StockCommission()                   
cerebro.broker.addcommissioninfo(comminfo)

# 通过调用 brokers 的 set_slippage_perc 方法设置百分比滑点
cerebro.broker.set_slippage_perc(perc=0.0001)



# data_ts_600519 = TS_Data(dataname=df_ts600519, fromdate=datetime.datetime(2010,9,1),
#                 todate=datetime.datetime(2010,12,30), nullvalue = None)
# data_ts_000001 = TS_Data(dataname=df_ts000001, fromdate=datetime.datetime(2010,9,1),
#                 todate=datetime.datetime(2010,12,30), nullvalue = None)

data_sql1 = TS_Data(dataname=df_sql1, fromdate=datetime.datetime(2025,1,1),todate=datetime.datetime(2025,8,8))
data_sql2 = TS_Data(dataname=df_sql2, fromdate=datetime.datetime(2025,1,1),todate=datetime.datetime(2025,8,8))
cerebro.adddata(data_sql1, name='000001')
cerebro.adddata(data_sql2, name='002594')

In [16]:
cerebro.addstrategy(TestStrategy1)
cerebro.run()

========                打印 self 策略本身的 lines                 ========
('datetime',)
========            打印 self.datas 第一个数据表格的 lines            ========
('close', 'low', 'high', 'open', 'volume', 'openinterest', 'datetime', 'pre_close', 'change', 'amount', 'extra')
========                     打印 最后一天数据                      ========
2025-08-08 00:00:00:	12.4	-0.5613
========                      打印 当天数据                       ========
date: 2025-01-09 00:00:00, data1 close: 11.40, data2 close: 269.39.
========                      打印 当天数据                       ========
date: 2025-01-10 00:00:00, data1 close: 11.30, data2 close: 266.02.
买买买
========                      打印 当天数据                       ========
date: 2025-01-13 00:00:00, data1 close: 11.20, data2 close: 266.00.
买买买
========                      打印 当天数据                       ========
date: 2025-01-14 00:00:00, data1 close: 11.38, data2 close: 276.30.
买买买
========                      打印 当天数据                       ========
date: 2025-01-15 00:00:00, data1 close: 11.48, data2 close: 274.69.
========                      打印 当天数据                       ========
date: 2025-01-16 00:00:00, data1 close: 11.57, data2 close: 272.76.
========                      打印 当天数据                       ========
date: 2025-01-17 00:00:00, data1 close: 11.45, data2 close: 276.60.
========                      打印 当天数据                       ========
date: 2025-01-20 00:00:00, data1 close: 11.42, data2 close: 284.43.
========                      打印 当天数据                       ========
date: 2025-01-21 00:00:00, data1 close: 11.33, data2 close: 286.05.
买买买
========                      打印 当天数据                       ========
date: 2025-01-22 00:00:00, data1 close: 11.09, data2 close: 282.50.
买买买
========                      打印 当天数据                       ========
date: 2025-01-23 00:00:00, data1 close: 11.32, data2 close: 277.11.
买买买
========                      打印 当天数据                       ========
date: 2025-01-24 00:00:00, data1 close: 11.34, data2 close: 279.08.
买买买
========                      打印 当天数据                       ========
date: 2025-01-27 00:00:00, data1 close: 11.47, data2 close: 274.50.
========                      打印 当天数据                       ========
date: 2025-02-05 00:00:00, data1 close: 11.37, data2 close: 282.80.
========                      打印 当天数据                       ========
date: 2025-02-06 00:00:00, data1 close: 11.36, data2 close: 311.08.
========                      打印 当天数据                       ========
date: 2025-02-07 00:00:00, data1 close: 11.38, data2 close: 326.90.
买买买
========                      打印 当天数据                       ========
date: 2025-02-10 00:00:00, data1 close: 11.43, data2 close: 330.13.
买买买
========                      打印 当天数据                       ========
date: 2025-02-11 00:00:00, data1 close: 11.42, data2 close: 329.90.
========                      打印 当天数据                       ========
date: 2025-02-12 00:00:00, data1 close: 11.42, data2 close: 345.05.
========                      打印 当天数据                       ========
date: 2025-02-13 00:00:00, data1 close: 11.50, data2 close: 341.30.
========                      打印 当天数据                       ========
date: 2025-02-14 00:00:00, data1 close: 11.55, data2 close: 356.05.
========                      打印 当天数据                       ========
date: 2025-02-17 00:00:00, data1 close: 11.78, data2 close: 348.50.
========                      打印 当天数据                       ========
date: 2025-02-18 00:00:00, data1 close: 11.81, data2 close: 356.22.
========                      打印 当天数据                       ========
date: 2025-02-19 00:00:00, data1 close: 11.71, data2 close: 358.50.
========                      打印 当天数据                       ========
date: 2025-02-20 00:00:00, data1 close: 11.66, data2 close: 362.78.
========                      打印 当天数据                       ========
date: 2025-02-21 00:00:00, data1 close: 11.64, data2 close: 383.00.
买买买
========                      打印 当天数据                       ========
date: 2025-02-24 00:00:00, data1 close: 11.59, data2 close: 376.28.
买买买
========                      打印 当天数据                       ========
date: 2025-02-25 00:00:00, data1 close: 11.47, data2 close: 372.49.
买买买
========                      打印 当天数据                       ========
date: 2025-02-26 00:00:00, data1 close: 11.52, data2 close: 372.10.
买买买
========                      打印 当天数据                       ========
date: 2025-02-27 00:00:00, data1 close: 11.62, data2 close: 375.50.
买买买
========                      打印 当天数据                       ========
date: 2025-02-28 00:00:00, data1 close: 11.53, data2 close: 361.82.
========                      打印 当天数据                       ========
date: 2025-03-03 00:00:00, data1 close: 11.51, data2 close: 360.21.
========                      打印 当天数据                       ========
date: 2025-03-04 00:00:00, data1 close: 11.51, data2 close: 344.84.
买买买
========                      打印 当天数据                       ========
date: 2025-03-05 00:00:00, data1 close: 11.66, data2 close: 353.96.
买买买
========                      打印 当天数据                       ========
date: 2025-03-06 00:00:00, data1 close: 11.63, data2 close: 358.93.
========                      打印 当天数据                       ========
date: 2025-03-07 00:00:00, data1 close: 11.67, data2 close: 356.40.
========                      打印 当天数据                       ========
date: 2025-03-10 00:00:00, data1 close: 11.59, data2 close: 351.00.
========                      打印 当天数据                       ========
date: 2025-03-11 00:00:00, data1 close: 11.61, data2 close: 350.38.
买买买
========                      打印 当天数据                       ========
date: 2025-03-12 00:00:00, data1 close: 11.85, data2 close: 351.00.
========                      打印 当天数据                       ========
date: 2025-03-13 00:00:00, data1 close: 11.84, data2 close: 354.50.
========                      打印 当天数据                       ========
date: 2025-03-14 00:00:00, data1 close: 11.97, data2 close: 375.94.
========                      打印 当天数据                       ========
date: 2025-03-17 00:00:00, data1 close: 11.50, data2 close: 380.25.
========                      打印 当天数据                       ========
date: 2025-03-18 00:00:00, data1 close: 11.49, data2 close: 384.57.
买买买
========                      打印 当天数据                       ========
date: 2025-03-19 00:00:00, data1 close: 11.52, data2 close: 397.07.
买买买
========                      打印 当天数据                       ========
date: 2025-03-20 00:00:00, data1 close: 11.49, data2 close: 399.99.
买买买
========                      打印 当天数据                       ========
date: 2025-03-21 00:00:00, data1 close: 11.42, data2 close: 372.00.
买买买
========                      打印 当天数据                       ========
date: 2025-03-24 00:00:00, data1 close: 11.38, data2 close: 375.36.
买买买
========                      打印 当天数据                       ========
date: 2025-03-25 00:00:00, data1 close: 11.43, data2 close: 369.59.
买买买
========                      打印 当天数据                       ========
date: 2025-03-26 00:00:00, data1 close: 11.38, data2 close: 376.01.
买买买
========                      打印 当天数据                       ========
date: 2025-03-27 00:00:00, data1 close: 11.39, data2 close: 386.50.
========                      打印 当天数据                       ========
date: 2025-03-28 00:00:00, data1 close: 11.35, data2 close: 382.50.
买买买
========                      打印 当天数据                       ========
date: 2025-03-31 00:00:00, data1 close: 11.26, data2 close: 374.90.
买买买
========                      打印 当天数据                       ========
date: 2025-04-01 00:00:00, data1 close: 11.27, data2 close: 365.50.
买买买
========                      打印 当天数据                       ========
date: 2025-04-02 00:00:00, data1 close: 11.37, data2 close: 360.50.
买买买
========                      打印 当天数据                       ========
date: 2025-04-03 00:00:00, data1 close: 11.34, data2 close: 357.51.
========                      打印 当天数据                       ========
date: 2025-04-07 00:00:00, data1 close: 10.70, data2 close: 321.76.
买买买
========                      打印 当天数据                       ========
date: 2025-04-08 00:00:00, data1 close: 10.82, data2 close: 327.51.
买买买
========                      打印 当天数据                       ========
date: 2025-04-09 00:00:00, data1 close: 10.80, data2 close: 324.60.
买买买
========                      打印 当天数据                       ========
date: 2025-04-10 00:00:00, data1 close: 10.90, data2 close: 336.40.
买买买
========                      打印 当天数据                       ========
date: 2025-04-11 00:00:00, data1 close: 10.89, data2 close: 354.98.
========                      打印 当天数据                       ========
date: 2025-04-14 00:00:00, data1 close: 10.93, data2 close: 359.00.
========                      打印 当天数据                       ========
date: 2025-04-15 00:00:00, data1 close: 10.95, data2 close: 359.97.
========                      打印 当天数据                       ========
date: 2025-04-16 00:00:00, data1 close: 11.00, data2 close: 352.15.
========                      打印 当天数据                       ========
date: 2025-04-17 00:00:00, data1 close: 11.06, data2 close: 349.68.
========                      打印 当天数据                       ========
date: 2025-04-18 00:00:00, data1 close: 11.18, data2 close: 346.00.
========                      打印 当天数据                       ========
date: 2025-04-21 00:00:00, data1 close: 11.02, data2 close: 348.76.
========                      打印 当天数据                       ========
date: 2025-04-22 00:00:00, data1 close: 11.04, data2 close: 354.84.
========                      打印 当天数据                       ========
date: 2025-04-23 00:00:00, data1 close: 11.01, data2 close: 371.99.
买买买
========                      打印 当天数据                       ========
date: 2025-04-24 00:00:00, data1 close: 11.03, data2 close: 366.00.
买买买
========                      打印 当天数据                       ========
date: 2025-04-25 00:00:00, data1 close: 11.01, data2 close: 370.83.
买买买
========                      打印 当天数据                       ========
date: 2025-04-28 00:00:00, data1 close: 11.00, data2 close: 360.00.
买买买
========                      打印 当天数据                       ========
date: 2025-04-29 00:00:00, data1 close: 10.98, data2 close: 355.00.
买买买
========                      打印 当天数据                       ========
date: 2025-04-30 00:00:00, data1 close: 10.91, data2 close: 353.09.
买买买
========                      打印 当天数据                       ========
date: 2025-05-06 00:00:00, data1 close: 10.96, data2 close: 359.96.
买买买
========                      打印 当天数据                       ========
date: 2025-05-07 00:00:00, data1 close: 11.03, data2 close: 359.20.
买买买
========                      打印 当天数据                       ========
date: 2025-05-08 00:00:00, data1 close: 11.08, data2 close: 359.28.
========                      打印 当天数据                       ========
date: 2025-05-09 00:00:00, data1 close: 11.15, data2 close: 363.22.
========                      打印 当天数据                       ========
date: 2025-05-12 00:00:00, data1 close: 11.16, data2 close: 370.28.
========                      打印 当天数据                       ========
date: 2025-05-13 00:00:00, data1 close: 11.29, data2 close: 366.50.
========                      打印 当天数据                       ========
date: 2025-05-14 00:00:00, data1 close: 11.43, data2 close: 373.10.
========                      打印 当天数据                       ========
date: 2025-05-15 00:00:00, data1 close: 11.39, data2 close: 376.80.
========                      打印 当天数据                       ========
date: 2025-05-16 00:00:00, data1 close: 11.38, data2 close: 389.17.
========                      打印 当天数据                       ========
date: 2025-05-19 00:00:00, data1 close: 11.37, data2 close: 382.81.
========                      打印 当天数据                       ========
date: 2025-05-20 00:00:00, data1 close: 11.39, data2 close: 394.80.
买买买
========                      打印 当天数据                       ========
date: 2025-05-21 00:00:00, data1 close: 11.48, data2 close: 400.00.
========                      打印 当天数据                       ========
date: 2025-05-22 00:00:00, data1 close: 11.55, data2 close: 398.80.
========                      打印 当天数据                       ========
date: 2025-05-23 00:00:00, data1 close: 11.46, data2 close: 405.00.
========                      打印 当天数据                       ========
date: 2025-05-26 00:00:00, data1 close: 11.42, data2 close: 381.00.
========                      打印 当天数据                       ========
date: 2025-05-27 00:00:00, data1 close: 11.49, data2 close: 372.41.
买买买
========                      打印 当天数据                       ========
date: 2025-05-28 00:00:00, data1 close: 11.53, data2 close: 362.88.
买买买
========                      打印 当天数据                       ========
date: 2025-05-29 00:00:00, data1 close: 11.46, data2 close: 361.13.
========                      打印 当天数据                       ========
date: 2025-05-30 00:00:00, data1 close: 11.56, data2 close: 352.30.
========                      打印 当天数据                       ========
date: 2025-06-03 00:00:00, data1 close: 11.81, data2 close: 356.00.
========                      打印 当天数据                       ========
date: 2025-06-04 00:00:00, data1 close: 11.84, data2 close: 360.52.
========                      打印 当天数据                       ========
date: 2025-06-05 00:00:00, data1 close: 11.67, data2 close: 360.75.
========                      打印 当天数据                       ========
date: 2025-06-06 00:00:00, data1 close: 11.70, data2 close: 359.96.
========                      打印 当天数据                       ========
date: 2025-06-09 00:00:00, data1 close: 11.71, data2 close: 348.14.
买买买
========                      打印 当天数据                       ========
date: 2025-06-10 00:00:00, data1 close: 11.81, data2 close: 353.13.
买买买
========                      打印 当天数据                       ========
date: 2025-06-11 00:00:00, data1 close: 11.85, data2 close: 361.99.
========                      打印 当天数据                       ========
date: 2025-06-12 00:00:00, data1 close: 11.68, data2 close: 353.24.
========                      打印 当天数据                       ========
date: 2025-06-13 00:00:00, data1 close: 11.58, data2 close: 346.00.
买买买
========                      打印 当天数据                       ========
date: 2025-06-16 00:00:00, data1 close: 11.79, data2 close: 344.43.
买买买
========                      打印 当天数据                       ========
date: 2025-06-17 00:00:00, data1 close: 11.76, data2 close: 343.74.
买买买
========                      打印 当天数据                       ========
date: 2025-06-18 00:00:00, data1 close: 11.77, data2 close: 346.95.
========                      打印 当天数据                       ========
date: 2025-06-19 00:00:00, data1 close: 11.70, data2 close: 340.50.
========                      打印 当天数据                       ========
date: 2025-06-20 00:00:00, data1 close: 11.84, data2 close: 340.25.
买买买
========                      打印 当天数据                       ========
date: 2025-06-23 00:00:00, data1 close: 11.93, data2 close: 338.20.
========                      打印 当天数据                       ========
date: 2025-06-24 00:00:00, data1 close: 11.93, data2 close: 343.38.
========                      打印 当天数据                       ========
date: 2025-06-25 00:00:00, data1 close: 12.06, data2 close: 349.27.
========                      打印 当天数据                       ========
date: 2025-06-26 00:00:00, data1 close: 12.41, data2 close: 337.44.
========                      打印 当天数据                       ========
date: 2025-06-27 00:00:00, data1 close: 12.20, data2 close: 334.24.
========                      打印 当天数据                       ========
date: 2025-06-30 00:00:00, data1 close: 12.07, data2 close: 331.91.
========                      打印 当天数据                       ========
date: 2025-07-01 00:00:00, data1 close: 12.30, data2 close: 331.34.
买买买
========                      打印 当天数据                       ========
date: 2025-07-02 00:00:00, data1 close: 12.32, data2 close: 330.66.
买买买
========                      打印 当天数据                       ========
date: 2025-07-03 00:00:00, data1 close: 12.35, data2 close: 334.56.
========                      打印 当天数据                       ========
date: 2025-07-04 00:00:00, data1 close: 12.60, data2 close: 331.00.
========                      打印 当天数据                       ========
date: 2025-07-07 00:00:00, data1 close: 12.78, data2 close: 328.59.
========                      打印 当天数据                       ========
date: 2025-07-08 00:00:00, data1 close: 12.69, data2 close: 326.88.
========                      打印 当天数据                       ========
date: 2025-07-09 00:00:00, data1 close: 12.84, data2 close: 325.80.
========                      打印 当天数据                       ========
date: 2025-07-10 00:00:00, data1 close: 13.18, data2 close: 321.23.
========                      打印 当天数据                       ========
date: 2025-07-11 00:00:00, data1 close: 12.91, data2 close: 323.91.
========                      打印 当天数据                       ========
date: 2025-07-14 00:00:00, data1 close: 12.98, data2 close: 318.49.
========                      打印 当天数据                       ========
date: 2025-07-15 00:00:00, data1 close: 12.73, data2 close: 323.05.
买买买
========                      打印 当天数据                       ========
date: 2025-07-16 00:00:00, data1 close: 12.64, data2 close: 323.72.
买买买
========                      打印 当天数据                       ========
date: 2025-07-17 00:00:00, data1 close: 12.59, data2 close: 328.02.
买买买
========                      打印 当天数据                       ========
date: 2025-07-18 00:00:00, data1 close: 12.70, data2 close: 329.11.
买买买
========                      打印 当天数据                       ========
date: 2025-07-21 00:00:00, data1 close: 12.61, data2 close: 334.12.
买买买
========                      打印 当天数据                       ========
date: 2025-07-22 00:00:00, data1 close: 12.49, data2 close: 341.69.
买买买
========                      打印 当天数据                       ========
date: 2025-07-23 00:00:00, data1 close: 12.53, data2 close: 338.07.
买买买
========                      打印 当天数据                       ========
date: 2025-07-24 00:00:00, data1 close: 12.35, data2 close: 342.72.
买买买
========                      打印 当天数据                       ========
date: 2025-07-25 00:00:00, data1 close: 12.35, data2 close: 337.93.
买买买
========                      打印 当天数据                       ========
date: 2025-07-28 00:00:00, data1 close: 12.46, data2 close: 337.00.
买买买
========                      打印 当天数据                       ========
date: 2025-07-29 00:00:00, data1 close: 12.34, data2 close: 111.42.
买买买
========                      打印 当天数据                       ========
date: 2025-07-30 00:00:00, data1 close: 12.49, data2 close: 108.70.
========                      打印 当天数据                       ========
date: 2025-07-31 00:00:00, data1 close: 12.23, data2 close: 105.24.
买买买
========                      打印 当天数据                       ========
date: 2025-08-01 00:00:00, data1 close: 12.28, data2 close: 105.80.
买买买
========                      打印 当天数据                       ========
date: 2025-08-04 00:00:00, data1 close: 12.30, data2 close: 104.88.
买买买
========                      打印 当天数据                       ========
date: 2025-08-05 00:00:00, data1 close: 12.47, data2 close: 104.86.
买买买
========                      打印 当天数据                       ========
date: 2025-08-06 00:00:00, data1 close: 12.46, data2 close: 104.35.
========                      打印 当天数据                       ========
date: 2025-08-07 00:00:00, data1 close: 12.47, data2 close: 105.33.
========                      打印 当天数据                       ========
date: 2025-08-08 00:00:00, data1 close: 12.40, data2 close: 103.93.

In [17]:
# 这是典型的 JupyterLab 4.x + matplotlib 后端 不匹配导致的前端 JS 报错。
# cerebro.plot() 在某些环境里会尝试用 “notebook/nbagg” 这种老前端（需要浏览器里有全局 IPython 对象），
# 而 JupyterLab 4.4.6 默认不再提供这个全局对象，所以就出现了 Javascript Error: IPython is not defined。
figs = cerebro.plot(iplot=False) 
plt.show()

2025-08-16 11:37:53.290 Python[53832:16110441] +[IMKClient subclass]: chose IMKClient_Modern
2025-08-16 11:37:53.290 Python[53832:16110441] +[IMKInputSession subclass]: chose IMKInputSession_Modern

KeyboardInterrupt:

In [ ]:
# 买卖demo

In [49]:

# -------- 1) A股佣金模型：佣金 + 卖出印花税(+可选过户费)，含最低佣金 5 元) --------
class AShareCommission(bt.CommInfoBase):
    params = (
        ('commission', 0.0003),   # 券商佣金，0.03%
        ('stamp_duty', 0.0005),   # 印花税，仅卖出收取 0.05%
        ('min_commission', 5.0),  # 单笔最低佣金 5 元（只作用于券商佣金部分）
        ('transfer_fee', 0.0),    # 过户费，可选：上证常见 0.00002，深证为 0。按成交额比例
        ('stocklike', True),
        ('commtype', bt.CommInfoBase.COMM_PERC),
    )

    def _getcommission(self, size, price, pseudoexec):
        # 成交额
        value = abs(size) * price

        # 券商佣金（含最低 5 元）
        broker_comm = max(value * self.p.commission, self.p.min_commission) if value > 0 else 0.0

        # 卖出印花税（仅卖出收）
        stamp = value * self.p.stamp_duty if size < 0 else 0.0

        # 过户费（买卖双向，按需要设置）
        transfer = value * self.p.transfer_fee if self.p.transfer_fee > 0 else 0.0

        return broker_comm + stamp + transfer


# -------- 2) A股下单手数：买入按 100 股整数倍，卖出不限 --------
class AShareSizer(bt.Sizer):
    params = (
        ('lot_size', 100),   # 一手=100股
        ('cash_keep', 0.00), # 预留现金比例（避免满仓导致佣金不足等）
    )

    def _getsizing(self, comminfo, cash, data, isbuy):
        # 决定下单数量
        price = data.close[0]

        if isbuy:
            # 可用预算（预留一点现金）
            budget = cash * (1 - self.p.cash_keep)
            if price <= 0:
                return 0
            # 以手为单位向下取整，再转回股数
            lots = int((budget / price) // self.p.lot_size)
            shares = lots * self.p.lot_size
            return max(shares, 0)
        else:
            # 卖出：返回当前持仓全部股数（A股允许非100倍数卖出）
            pos = self.broker.getposition(data)
            return int(pos.size)


# -------- 3) T+1 示例策略：当日买入，次日才能卖出 --------
class T1ExampleStrategy(bt.Strategy):
    params = dict(
        pfast=10, pslow=20,
    )

    def __init__(self):
        self.sma_fast = bt.ind.SMA(self.data.close, period=self.p.pfast)
        self.sma_slow = bt.ind.SMA(self.data.close, period=self.p.pslow)

        # 记录最近一次“买入完成”的交易日（用于T+1）
        self.last_buy_date = None

    def notify_order(self, order):
        if order.status in [order.Completed]:
            odt = bt.num2date(order.executed.dt).date()
            if order.isbuy():
                # 记录买入完成的日期
                self.last_buy_date = odt

    def can_sell_today(self):
        """T+1：如果今天与最近买入完成是同一天，则不能卖出。"""
        if self.position.size <= 0:
            return False  # 没有持仓无需卖
        if self.last_buy_date is None:
            return True   # 没买过，自由卖
        today = self.data.datetime.date(0)
        return self.last_buy_date < today  # 只有过了一天才可卖

    def next(self):
        # 简单金叉买、死叉卖（演示），加上 T+1 约束
        if not self.position:
            if bt.ind.CrossOver(self.sma_fast, self.sma_slow)[0] > 0:
                self.buy()  # 具体买入数量由 sizer 控制成 100 的整数倍
        else:
            # 死叉出现且满足T+1才卖
            if bt.ind.CrossOver(self.sma_fast, self.sma_slow)[0] < 0 and self.can_sell_today():
                self.sell()


    return results

In [50]:
# Create a Stratey
class TestStrategy(bt.Strategy):

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

        # To keep track of pending orders
        self.order = None

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enough cash
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log('BUY EXECUTED, %.2f' % order.executed.price)
            elif order.issell():
                self.log('SELL EXECUTED, %.2f' % order.executed.price)

            self.bar_executed = len(self)

        elif order.status in [order.Canceled]:
            self.log('Order Canceled')
        elif order.status in [order.Margin]:
            self.log('Order Margin')
        elif order.status in [order.Rejected]:
            self.log('Order Rejected')

        # Write down: no pending order
        self.order = None

    def next(self):
        # Simply log the closing price of the series from the reference
        self.log('Close, %.2f' % self.dataclose[0])

        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return

        # Check if we are in the market
        if not self.position:

            # Not yet ... we MIGHT BUY if ...
            if self.dataclose[0] < self.dataclose[-1]:
                    # current close less than previous close

                    if self.dataclose[-1] < self.dataclose[-2]:
                        # previous close less than the previous close

                        # BUY, BUY, BUY!!! (with default parameters)
                        self.log('BUY CREATE, %.2f' % self.dataclose[0])

                        # Keep track of the created order to avoid a 2nd order
                        self.order = self.buy()

        else:

            # Already in the market ... we might sell
            if len(self) >= (self.bar_executed + 5):
                # SELL, SELL, SELL!!! (with all possible default parameters)
                self.log('SELL CREATE, %.2f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()

In [54]:
# 初始化 交易
cerebro = bt.Cerebro()
# 设置初始资金
cerebro.broker.setcash(10000000.0)
cerebro.broker.getcash() # 获取当前可用资金

# 加入A股佣金模型（可按需调整参数）
comminfo = AShareCommission(
    commission=0.0003,      # 券商佣金 0.03%
    stamp_duty=0.0005,      # 卖出印花税 0.05%
    min_commission=5.0,     # 最低佣金 5 元
    transfer_fee=0.0        # 如需上证过户费可设为0.00002
)
cerebro.broker.addcommissioninfo(comminfo)

# A股手数控制（买入 100 股的整数倍）
cerebro.addsizer(AShareSizer, lot_size=100, cash_keep=0.8)

# 通过调用 brokers 的 set_slippage_perc 方法设置百分比滑点
cerebro.broker.set_slippage_perc(perc=0.0001)



# data_ts_600519 = TS_Data(dataname=df_ts600519, fromdate=datetime.datetime(2010,9,1),
#                 todate=datetime.datetime(2010,12,30), nullvalue = None)
# data_ts_000001 = TS_Data(dataname=df_ts000001, fromdate=datetime.datetime(2010,9,1),
#                 todate=datetime.datetime(2010,12,30), nullvalue = None)

data_sql1 = TS_Data(dataname=df_sql1, fromdate=datetime.datetime(2025,1,1),todate=datetime.datetime(2025,8,8))
data_sql2 = TS_Data(dataname=df_sql2, fromdate=datetime.datetime(2025,1,1),todate=datetime.datetime(2025,8,8))
cerebro.adddata(data_sql1, name='000001')
# cerebro.adddata(data_sql2, name='002594')

In [55]:
cerebro.addstrategy(TestStrategy)
cerebro.run()

2025-01-02, Close, 11.43
2025-01-02, BUY CREATE, 11.43
2025-01-03, BUY EXECUTED, 11.44
2025-01-03, Close, 11.38
2025-01-06, Close, 11.44
2025-01-07, Close, 11.51
2025-01-08, Close, 11.50
2025-01-09, Close, 11.40
2025-01-10, Close, 11.30
2025-01-10, SELL CREATE, 11.30
2025-01-13, SELL EXECUTED, 11.25
2025-01-13, Close, 11.20
2025-01-13, BUY CREATE, 11.20
2025-01-14, BUY EXECUTED, 11.20
2025-01-14, Close, 11.38
2025-01-15, Close, 11.48
2025-01-16, Close, 11.57
2025-01-17, Close, 11.45
2025-01-20, Close, 11.42
2025-01-21, Close, 11.33
2025-01-21, SELL CREATE, 11.33
2025-01-22, SELL EXECUTED, 11.32
2025-01-22, Close, 11.09
2025-01-22, BUY CREATE, 11.09
2025-01-23, BUY EXECUTED, 11.17
2025-01-23, Close, 11.32
2025-01-24, Close, 11.34
2025-01-27, Close, 11.47
2025-02-05, Close, 11.37
2025-02-06, Close, 11.36
2025-02-07, Close, 11.38
2025-02-07, SELL CREATE, 11.38
2025-02-10, SELL EXECUTED, 11.38
2025-02-10, Close, 11.43
2025-02-11, Close, 11.42
2025-02-12, Close, 11.42
2025-02-13, Close, 11.50
2025-02-14, Close, 11.55
2025-02-17, Close, 11.78
2025-02-18, Close, 11.81
2025-02-19, Close, 11.71
2025-02-20, Close, 11.66
2025-02-20, BUY CREATE, 11.66
2025-02-21, BUY EXECUTED, 11.69
2025-02-21, Close, 11.64
2025-02-24, Close, 11.59
2025-02-25, Close, 11.47
2025-02-26, Close, 11.52
2025-02-27, Close, 11.62
2025-02-28, Close, 11.53
2025-02-28, SELL CREATE, 11.53
2025-03-03, SELL EXECUTED, 11.52
2025-03-03, Close, 11.51
2025-03-03, BUY CREATE, 11.51
2025-03-04, BUY EXECUTED, 11.47
2025-03-04, Close, 11.51
2025-03-05, Close, 11.66
2025-03-06, Close, 11.63
2025-03-07, Close, 11.67
2025-03-10, Close, 11.59
2025-03-11, Close, 11.61
2025-03-11, SELL CREATE, 11.61
2025-03-12, SELL EXECUTED, 11.60
2025-03-12, Close, 11.85
2025-03-13, Close, 11.84
2025-03-14, Close, 11.97
2025-03-17, Close, 11.50
2025-03-18, Close, 11.49
2025-03-18, BUY CREATE, 11.49
2025-03-19, BUY EXECUTED, 11.48
2025-03-19, Close, 11.52
2025-03-20, Close, 11.49
2025-03-21, Close, 11.42
2025-03-24, Close, 11.38
2025-03-25, Close, 11.43
2025-03-26, Close, 11.38
2025-03-26, SELL CREATE, 11.38
2025-03-27, SELL EXECUTED, 11.37
2025-03-27, Close, 11.39
2025-03-28, Close, 11.35
2025-03-31, Close, 11.26
2025-03-31, BUY CREATE, 11.26
2025-04-01, BUY EXECUTED, 11.27
2025-04-01, Close, 11.27
2025-04-02, Close, 11.37
2025-04-03, Close, 11.34
2025-04-07, Close, 10.70
2025-04-08, Close, 10.82
2025-04-09, Close, 10.80
2025-04-09, SELL CREATE, 10.80
2025-04-10, SELL EXECUTED, 10.86
2025-04-10, Close, 10.90
2025-04-11, Close, 10.89
2025-04-14, Close, 10.93
2025-04-15, Close, 10.95
2025-04-16, Close, 11.00
2025-04-17, Close, 11.06
2025-04-18, Close, 11.18
2025-04-21, Close, 11.02
2025-04-22, Close, 11.04
2025-04-23, Close, 11.01
2025-04-24, Close, 11.03
2025-04-25, Close, 11.01
2025-04-28, Close, 11.00
2025-04-28, BUY CREATE, 11.00
2025-04-29, BUY EXECUTED, 11.00
2025-04-29, Close, 10.98
2025-04-30, Close, 10.91
2025-05-06, Close, 10.96
2025-05-07, Close, 11.03
2025-05-08, Close, 11.08
2025-05-09, Close, 11.15
2025-05-09, SELL CREATE, 11.15
2025-05-12, SELL EXECUTED, 11.16
2025-05-12, Close, 11.16
2025-05-13, Close, 11.29
2025-05-14, Close, 11.43
2025-05-15, Close, 11.39
2025-05-16, Close, 11.38
2025-05-16, BUY CREATE, 11.38
2025-05-19, BUY EXECUTED, 11.40
2025-05-19, Close, 11.37
2025-05-20, Close, 11.39
2025-05-21, Close, 11.48
2025-05-22, Close, 11.55
2025-05-23, Close, 11.46
2025-05-26, Close, 11.42
2025-05-26, SELL CREATE, 11.42
2025-05-27, SELL EXECUTED, 11.45
2025-05-27, Close, 11.49
2025-05-28, Close, 11.53
2025-05-29, Close, 11.46
2025-05-30, Close, 11.56
2025-06-03, Close, 11.81
2025-06-04, Close, 11.84
2025-06-05, Close, 11.67
2025-06-06, Close, 11.70
2025-06-09, Close, 11.71
2025-06-10, Close, 11.81
2025-06-11, Close, 11.85
2025-06-12, Close, 11.68
2025-06-13, Close, 11.58
2025-06-13, BUY CREATE, 11.58
2025-06-16, BUY EXECUTED, 11.57
2025-06-16, Close, 11.79
2025-06-17, Close, 11.76
2025-06-18, Close, 11.77
2025-06-19, Close, 11.70
2025-06-20, Close, 11.84
2025-06-23, Close, 11.93
2025-06-23, SELL CREATE, 11.93
2025-06-24, SELL EXECUTED, 11.90
2025-06-24, Close, 11.93
2025-06-25, Close, 12.06
2025-06-26, Close, 12.41
2025-06-27, Close, 12.20
2025-06-30, Close, 12.07
2025-06-30, BUY CREATE, 12.07
2025-07-01, BUY EXECUTED, 12.06
2025-07-01, Close, 12.30
2025-07-02, Close, 12.32
2025-07-03, Close, 12.35
2025-07-04, Close, 12.60
2025-07-07, Close, 12.78
2025-07-08, Close, 12.69
2025-07-08, SELL CREATE, 12.69
2025-07-09, SELL EXECUTED, 12.66
2025-07-09, Close, 12.84
2025-07-10, Close, 13.18
2025-07-11, Close, 12.91
2025-07-14, Close, 12.98
2025-07-15, Close, 12.73
2025-07-16, Close, 12.64
2025-07-16, BUY CREATE, 12.64
2025-07-17, BUY EXECUTED, 12.61
2025-07-17, Close, 12.59
2025-07-18, Close, 12.70
2025-07-21, Close, 12.61
2025-07-22, Close, 12.49
2025-07-23, Close, 12.53
2025-07-24, Close, 12.35
2025-07-24, SELL CREATE, 12.35
2025-07-25, SELL EXECUTED, 12.33
2025-07-25, Close, 12.35
2025-07-28, Close, 12.46
2025-07-29, Close, 12.34
2025-07-30, Close, 12.49
2025-07-31, Close, 12.23
2025-08-01, Close, 12.28
2025-08-04, Close, 12.30
2025-08-05, Close, 12.47
2025-08-06, Close, 12.46
2025-08-07, Close, 12.47
2025-08-08, Close, 12.40

In [56]:
plt.ion()  
figs = cerebro.plot(iplot=False) 
plt.show(block=False)
plt.pause(0.001) 
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

Final Portfolio Value: 10059602.31

In [48]:
df_sql1[(df_sql1.trade_date>="20250101") & (df_sql1.trade_date<="20250220")]

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,date
3573,000001.SZ,20250102,11.73,11.77,11.39,11.43,11.70,-0.27,-2.3077,1819600.0,2102920.0,2025-01-02
3574,000001.SZ,20250103,11.44,11.54,11.36,11.38,11.43,-0.05,-0.4374,1154680.0,1320520.0,2025-01-03
3575,000001.SZ,20250106,11.38,11.48,11.22,11.44,11.38,0.06,0.5272,1085540.0,1234310.0,2025-01-06
3576,000001.SZ,20250107,11.42,11.53,11.37,11.51,11.44,0.07,0.6119,747863.0,858329.0,2025-01-07
3577,000001.SZ,20250108,11.50,11.63,11.40,11.50,11.51,-0.01,-0.0869,1062390.0,1223600.0,2025-01-08
3578,000001.SZ,20250109,11.50,11.50,11.35,11.40,11.50,-0.10,-0.8696,751483.0,857836.0,2025-01-09
3579,000001.SZ,20250110,11.40,11.46,11.28,11.30,11.40,-0.10,-0.8772,798134.0,905005.0,2025-01-10
3580,000001.SZ,20250113,11.25,11.26,11.08,11.20,11.30,-0.10,-0.8850,934966.0,1044900.0,2025-01-13
3581,000001.SZ,20250114,11.20,11.40,11.19,11.38,11.20,0.18,1.6071,824629.0,934468.0,2025-01-14
3582,000001.SZ,20250115,11.38,11.58,11.36,11.48,11.38,0.10,0.8787,1031630.0,1185400.0,2025-01-15
3583,000001.SZ,20250116,11.55,11.59,11.47,11.57,11.48,0.09,0.7840,872964.0,1007690.0,2025-01-16
3584,000001.SZ,20250117,11.53,11.55,11.42,11.45,11.57,-0.12,-1.0372,689765.0,791230.0,2025-01-17
3585,000001.SZ,20250120,11.50,11.52,11.40,11.42,11.45,-0.03,-0.2620,832029.0,953092.0,2025-01-20
3586,000001.SZ,20250121,11.45,11.45,11.32,11.33,11.42,-0.09,-0.7881,902069.0,1024880.0,2025-01-21
3587,000001.SZ,20250122,11.32,11.33,11.08,11.09,11.33,-0.24,-2.1183,1347130.0,1504820.0,2025-01-22
3588,000001.SZ,20250123,11.17,11.40,11.17,11.32,11.09,0.23,2.0739,1514920.0,1715170.0,2025-01-23
3589,000001.SZ,20250124,11.32,11.39,11.22,11.34,11.32,0.02,0.1767,944944.0,1069900.0,2025-01-24
3590,000001.SZ,20250127,11.38,11.55,11.38,11.47,11.34,0.13,1.1464,1151930.0,1324270.0,2025-01-27
3591,000001.SZ,20250205,11.50,11.52,11.33,11.37,11.47,-0.10,-0.8718,843434.0,961194.0,2025-02-05
3592,000001.SZ,20250206,11.35,11.45,11.30,11.36,11.37,-0.01,-0.0880,955603.0,1084790.0,2025-02-06
3593,000001.SZ,20250207,11.36,11.45,11.31,11.38,11.36,0.02,0.1761,1407490.0,1601620.0,2025-02-07
3594,000001.SZ,20250210,11.38,11.50,11.36,11.43,11.38,0.05,0.4394,1026590.0,1174040.0,2025-02-10
3595,000001.SZ,20250211,11.40,11.47,11.37,11.42,11.43,-0.01,-0.0875,844520.0,963866.0,2025-02-11
3596,000001.SZ,20250212,11.41,11.43,11.34,11.42,11.42,0.00,0.0000,988807.0,1125320.0,2025-02-12
3597,000001.SZ,20250213,11.42,11.55,11.40,11.50,11.42,0.08,0.7005,1358640.0,1560710.0,2025-02-13
3598,000001.SZ,20250214,11.49,11.55,11.43,11.55,11.50,0.05,0.4348,973058.0,1118360.0,2025-02-14
3599,000001.SZ,20250217,11.60,11.80,11.55,11.78,11.55,0.23,1.9913,2061970.0,2413150.0,2025-02-17
3600,000001.SZ,20250218,11.76,11.96,11.76,11.81,11.78,0.03,0.2547,1996610.0,2371070.0,2025-02-18
3601,000001.SZ,20250219,11.80,11.81,11.68,11.71,11.81,-0.10,-0.8467,1177750.0,1382470.0,2025-02-19
3602,000001.SZ,20250220,11.71,11.76,11.65,11.66,11.71,-0.05,-0.4270,784396.0,917231.0,2025-02-20

In [34]:
df_sql2[(df_sql2.trade_date>="20250720") & (df_sql2.trade_date<="20250730")]

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,date
3402,002594.SZ,20250721,327.99,334.12,327.26,334.12,329.11,5.01,1.5223,153945.0,5102460.0,2025-07-21
3403,002594.SZ,20250722,335.00,342.01,333.21,341.69,334.12,7.57,2.2657,214164.0,7227730.0,2025-07-22
3404,002594.SZ,20250723,342.09,343.00,337.00,338.07,341.69,-3.62,-1.0594,158907.0,5395840.0,2025-07-23
3405,002594.SZ,20250724,338.08,346.54,337.63,342.72,338.07,4.65,1.3755,189063.0,6489370.0,2025-07-24
3406,002594.SZ,20250725,341.00,341.40,335.00,337.93,342.72,-4.79,-1.3976,157041.0,5307870.0,2025-07-25
3407,002594.SZ,20250728,337.93,339.10,335.53,337.00,337.93,-0.93,-0.2752,117057.0,3947000.0,2025-07-28
3408,002594.SZ,20250729,112.01,112.50,109.77,111.42,111.01,0.41,0.3693,387360.0,4322740.0,2025-07-29
3409,002594.SZ,20250730,108.05,111.16,107.12,108.70,111.42,-2.72,-2.4412,524834.0,5743880.0,2025-07-30